/* THIS FILE WAS GENERATED FOLLOWING THE OFFICIAL PAYLOAD 3 TEMPLATE. DO NOT MODIFY IT BECAUSE IT COULD BE REWRITTEN AT ANY TIME. */
import config from '@payload-config'
import { GRAPHQL_PLAYGROUND_GET } from '@payloadcms/next/routes'

export const GET = GRAPHQL_PLAYGROUND_GET(config)
