// Post 29 (dynamic-programming) rewritten block content. See _pf-data-28.ts for conventions.
// Blocks 39-56 (es) are a pseudo-table implemented as flat paragraphs (Problema/Complejidad/
// Descripción columns) rather than a real Lexical `table` node -- a pre-existing layout bug,
// out of scope for this voice-rewrite plan. Left untouched (not listed below -> pass through).

export const post29: Record<'es' | 'en', Record<number, string>> = {
  es: {
    1: 'La ⟦L⟧ es una técnica clave para construir ⟦L⟧ eficientes: descompone problemas complejos en subproblemas manejables. En esta guía reviso sus fundamentos, las estrategias de implementación y algunas ⟦L⟧.',
    2: "Cubro desde la subsecuencia creciente máxima hasta el 'edit distance dynamic programming', con la idea de dejar un marco claro para aplicar esta técnica en distintos escenarios.",
    5: 'La ⟦L⟧ resuelve problemas complejos descomponiéndolos en subproblemas más simples, apoyada en dos principios: optimalidad de subestructuras y solapamiento de subproblemas. El primero dice que la solución óptima de un problema se construye a partir de las soluciones óptimas de sus subproblemas. El segundo, que muchos subproblemas se repiten durante la resolución, así que conviene guardar sus soluciones en vez de recalcularlas cada vez.',
    7: 'La ventaja principal está en el tiempo de ejecución frente a un enfoque más ingenuo, como la recursión simple. Guardar los resultados ya resueltos baja la complejidad de exponencial a polinómica. Es el caso, por ejemplo, de la distancia de edición (edit distance), donde hay que encontrar el mínimo de operaciones para transformar una cadena en otra, algo que se resuelve bien con tabulación o memoización.',
    9: 'Frente a la fuerza bruta, que explora todas las combinaciones posibles, la programación dinámica ataca el problema de forma más estructurada. El ⟦L⟧ greedy es otro punto de comparación: toma la mejor decisión en cada paso, pero no garantiza una solución globalmente óptima, algo que la programación dinámica sí logra al considerar todas las subestructuras.',
    11: 'Hay varias formas de implementar programación dinámica, cada una con sus ventajas y desventajas, y elegir la correcta depende del problema que tengas enfrente.',
    13: 'El enfoque top-down parte del problema original y lo va descomponiendo en subproblemas más chicos. Si un subproblema ya se resolvió antes, se reutiliza su solución guardada: esto es la memoización. Es intuitivo y fácil de implementar, un buen punto de entrada para quien recién empieza con programación dinámica.',
    15: 'Bottom-up hace lo contrario: resuelve primero los subproblemas más simples y los va combinando hasta llegar al problema original, así que todo lo necesario ya está calculado cuando toca abordar el caso general. Normalmente se implementa con ⟦L⟧ como tablas o matrices donde se guardan los resultados intermedios. Funciona muy bien cuando hay una relación clara entre subproblemas, como en el cálculo del edit distance dynamic programming.',
    17: 'Memoización y tabulación son las dos técnicas que se usan para guardar soluciones a subproblemas, aunque cada una lo hace de forma distinta.',
    18: 'Memoización: sigue el enfoque top-down. Resuelve los subproblemas según se necesitan y guarda sus resultados para después. Es más flexible, pero puede gastar más memoria si al inicio hay muchos subproblemas sin calcular.',
    19: 'Tabulación: sigue el enfoque bottom-up. Construye una tabla con las soluciones de todos los subproblemas, desde el más simple hasta el problema final. Exige más planificación de entrada, pero suele ser más eficiente en tiempo y memoria.',
    20: 'Cuál conviene depende del problema y de la preferencia de quien programa: la elección entre memoización y tabulación afecta directamente el rendimiento y qué tan fácil es desarrollar el algoritmo. Casos como el edit distance dynamic programming muestran por qué la programación dinámica sigue siendo una herramienta clave en la informática.',
    22: 'A continuación reviso algunos de los problemas clásicos donde la programación dinámica se aplica de forma más directa.',
    24: 'Este problema busca la subsecuencia ordenada más larga dentro de una secuencia dada. Se resuelve manteniendo un arreglo que guarda la máxima longitud encontrada en cada posición, con una complejidad temporal de O(n²).',
    26: 'Un clásico de optimización combinatoria: maximizar el valor de los objetos que caben en una mochila con peso limitado. Se resuelve con una matriz que rastrea combinaciones de peso y valor, calculando con un enfoque bottom-up si conviene o no incluir cada objeto. La complejidad es O(nW), donde n es el número de objetos y W la capacidad de la mochila.',
    28: 'Floyd-Warshall encuentra los caminos más cortos entre todos los pares de nodos de un grafo, dirigido o no. Actualiza las distancias de forma iterativa, probando cada nodo como posible intermediario, con una complejidad de O(n³).',
    30: 'Compara dos cadenas para encontrar la subsecuencia más larga que tienen en común, usando una tabla bidimensional para construir la solución. La complejidad es O(m·n), con m y n como las longitudes de ambas cadenas.',
    32: 'La distancia de edición mide cuántas operaciones (inserciones, eliminaciones o sustituciones) hacen falta para transformar una cadena en otra. Con programación dinámica se construye una matriz donde cada celda es el costo de transformar una subcadena en otra, con complejidad O(m·n).',
    33: '1. Definición y usos en comparación de cadenas',
    34: 'Se usa mucho en procesamiento de texto y bioinformática, donde hace falta comparar cadenas con precisión, y ayuda a optimizar algoritmos de coincidencia de patrones y alineación de secuencias.',
    35: '2. Algoritmo de Levenshtein: implementación y optimización',
    36: 'Levenshtein es una variante de este problema centrada en contar el mínimo de operaciones para convertir una cadena en otra. Se puede optimizar con tabulación para ahorrar espacio, manteniendo la complejidad en O(m·n).',
    37: '3. Variantes y aplicaciones avanzadas',
    38: 'Hay variantes que asignan pesos distintos a cada operación (inserción, eliminación) y también se usa en aprendizaje automático y procesamiento de lenguaje natural.',
  },
  en: {
    0: "⟦L⟧ tackles complex problems by breaking them into simpler subproblems. This guide covers the core principles and the different approaches you'll actually use.",
    1: 'The focus here is practical: dynamic programming in Python, and how to actually optimize a solution instead of just describing it.',
    4: "Dynamic programming solves problems that break down into simpler, overlapping subproblems. It's especially useful when the same subproblem shows up more than once, since you can reuse a result instead of recomputing it. That's really the whole idea: keep the solutions you already found, and skip the redundant work.",
    6: "Two properties make a problem a good fit: optimal substructure, where the optimal solution is built from optimal solutions to its subproblems, and overlapping subproblems, where the same subproblem gets solved more than once. Fibonacci, the knapsack problem, and longest common subsequence are the classic examples. Both properties are what let dynamic programming cut ⟦L⟧ compared to a naive recursive approach.",
    8: "These two concepts are worth separating clearly. Overlapping subproblems means the same subproblem gets solved repeatedly while working toward the larger solution, which is the whole reason dynamic programming is efficient. Optimal substructure means you can build the optimal solution from the optimal solutions of the subproblems. Get comfortable with both, and applying dynamic programming in Python starts to feel a lot less like magic.",
    10: 'There are two main approaches, each with its own trade-offs: top-down, known as memoization, and bottom-up, known as tabulation. Knowing when to reach for each one matters more than memorizing the definitions.',
    12: "Top-down is recursive: you start at the main problem and break it down into smaller ones, caching each result the first time you compute it so you never redo the work. It's intuitive because it mirrors how you'd naturally think through the recursion, and in Python, decorators or a plain hash map are usually enough to implement it.",
    14: 'Bottom-up flips it around: solve the smallest subproblems first and iteratively build up to the final answer, with no recursion involved. You store results in a table or array, which avoids function call overhead and guarantees every subproblem is computed exactly once. In Python, a plain list with straightforward indexing is usually all you need.',
    16: "Top-down tends to be more intuitive if you're newer to this, since it follows the recursion you'd already be thinking in. Bottom-up usually wins on space and time complexity, since a table avoids all the function call overhead. Both work fine in Python. Which one to use just depends on the problem in front of you.",
    18: "Python makes both approaches easy to implement, mostly because of a couple of language features worth knowing well. Here's how that plays out in practice.",
    20: "Python decorators make memoization pretty clean to implement. Here's the general shape of it:",
    24: 'This keeps the code readable while still speeding things up. In practice, you can skip writing this by hand and just use the built-in functools.lru_cache for automatic memoization.',
    26: 'For bottom-up, you solve subproblems iteratively starting from the simplest, storing intermediate results in a Python list or array. The steps usually look like:',
    30: 'Every subproblem gets solved exactly once this way, which is where the time complexity savings come from.',
    32: "There's usually a trade-off between time and space complexity, and Python gives you a couple of ways to tune both:",
    35: 'Looking closely at what the problem actually requires usually reveals which variables you can drop or compress, which is where the real efficiency gains come from.',
    37: 'A few patterns come up again and again when implementing dynamic programming in Python:',
    41: 'Recognizing these patterns early saves a lot of time once you are actually solving new problems.',
    43: "Longest Increasing Subsequence (LIS) is the classic example everyone uses to learn this. Here's the outline:",
    47: 'This runs in O(n²), though you can push it down further with binary search if you need the extra speed.',
  },
}
