// Post 30 (binary-search-tree) rewritten block content. See _pf-data-28.ts for conventions.
//
// KNOWN PRE-EXISTING BUG (documented in SUMMARY, fixed here as Rule 1): the live `en` locale
// content for this post was actually written in Spanish (confirmed against title.en too, which
// is out of this plan's scope and left untouched). Since this script already rewrites the `en`
// locale's content field, the rewrite below is genuine English, correcting the language bug in
// the same pass -- not a separate, unauthorized edit.

export const post30: Record<'es' | 'en', Record<number, string>> = {
  es: {
    0: 'Un árbol de búsqueda binaria (BST) es una ⟦L⟧ que organiza datos aprovechando una propiedad de orden simple: cada nodo tiene un valor único, los del subárbol izquierdo son menores y los del derecho son mayores. Esa sola regla es lo que hace eficientes la búsqueda, la inserción y la eliminación de nodos.',
    2: 'Antes de entrar en operaciones, vale la pena repasar la estructura básica de un BST y cómo esa estructura termina definiendo el rendimiento de todo lo demás.',
    4: 'En su forma más básica, un BST es un árbol binario: nodos conectados jerárquicamente, cada uno con un valor y hasta dos punteros, uno al hijo izquierdo y otro al derecho. Esa jerarquía es la que sostiene la relación de orden entre nodos.',
    6: 'La regla es siempre la misma: todo el subárbol izquierdo de un nodo tiene valores estrictamente menores, y todo el subárbol derecho, valores mayores. Esta propiedad es la base de toda búsqueda eficiente en el árbol.',
    8: 'Cada valor en el árbol debe ser único, sin excepciones. Esa restricción evita duplicados y hace que cada subárbol, por sí mismo, siga cumpliendo las propiedades de un BST.',
    10: 'La altura del árbol es lo que determina su rendimiento real. Un árbol equilibrado, con altura mínima, da acceso rápido a cualquier nodo. Uno desequilibrado puede disparar el tiempo de respuesta y arruinar esa eficiencia.',
    12: 'Las operaciones que importan de verdad en un BST son tres: buscar, insertar y eliminar nodos sin romper la propiedad de orden del árbol.',
    14: 'Buscar un valor en un BST se puede hacer de forma iterativa o recursiva. En ambos casos se parte de la raíz y se va comparando el valor buscado con los nodos del camino.',
    16: 'El proceso, paso a paso:',
    23: 'En el peor caso, si el BST termina desbalanceado (por ejemplo, degenerado en una lista enlazada), la complejidad sube a O(n), con n como el número de nodos.',
    25: 'Insertar en un BST sigue un método que garantiza que el orden de los nodos se mantenga intacto.',
    27: 'El proceso es parecido al de la búsqueda:',
    33: 'El problema típico aparece cuando se intenta insertar un valor duplicado, algo que un BST no permite.',
    35: 'Eliminar un nodo es más delicado: el procedimiento cambia según cuántos hijos tenga el nodo que se quiere quitar.',
    37: 'Si el nodo no tiene hijos, se elimina directamente, sin más trámite.',
    39: 'Con un solo hijo, se elimina el nodo y se conecta ese hijo directamente con el padre del nodo eliminado.',
    41: 'Con dos hijos, se reemplaza el valor del nodo por el menor del subárbol derecho o el mayor del izquierdo. Así el árbol conserva su propiedad de orden incluso durante la eliminación.',
    43: 'Por qué importa el balance',
    44: 'Un BST balanceado mejora la eficiencia de la búsqueda, la inserción y la eliminación simplemente porque mantiene la altura del árbol en niveles óptimos.',
    46: 'Sin balance, un BST puede degenerar en algo parecido a una lista enlazada, con todas las operaciones cayendo a O(n). El balance es lo único que garantiza tiempos aceptables.',
    48: 'Un árbol AVL es un BST balanceado que garantiza que la diferencia de altura entre el subárbol izquierdo y el derecho de cualquier nodo nunca pase de uno.',
    54: 'Las rotaciones son la técnica para recuperar el equilibrio: rotación simple o rotación doble, según cómo estén desbalanceados los nodos.',
    56: 'El árbol rojo-negro es otra variante balanceada, con reglas propias que garantizan que el camino más largo desde la raíz hasta una hoja nunca sea más del doble del camino más corto.',
    63: 'Insertar o eliminar en un árbol rojo-negro implica recoloraciones y rotaciones para no romper ninguna de sus reglas.',
    65: 'La diferencia se reduce a eficiencia: los árboles balanceados mantienen tiempos logarítmicos, mientras que los no balanceados pueden caer a tiempos lineales. Con grandes volúmenes de datos, donde la velocidad de acceso importa, conviene siempre el balanceado.',
    67: 'Los recorridos son la forma de acceder y procesar los nodos de un BST, y hay varios métodos, cada uno pensado para un uso distinto.',
    69: 'El recorrido inorden visita primero el subárbol izquierdo, luego el nodo actual y por último el subárbol derecho. El resultado es una lista de valores en orden ascendente, sin ningún esfuerzo extra.',
    71: 'Gracias a la propiedad del BST, recorrer los nodos en este orden entrega los valores de menor a mayor sin necesidad de ordenar nada aparte. Es útil cada vez que una operación necesita datos ya ordenados.',
    73: 'El recorrido preorden visita primero el nodo actual, después el subárbol izquierdo y luego el derecho. Se usa sobre todo para copiar árboles o serializarlos.',
    75: 'Con un recorrido preorden se obtiene una representación completa del árbol que permite recrearlo en otro contexto sin perder la jerarquía. Es clave en ⟦L⟧ donde hace falta transmitir la estructura original de los datos.',
    77: 'El recorrido postorden visita primero los nodos hijos y al final el nodo actual. Funciona bien cuando hay que evaluar una expresión o liberar recursos en el orden correcto.',
    79: 'Por eso es clave para eliminar nodos: garantiza que los hijos se procesen antes que el padre. También sirve para evaluar árboles de expresión, donde el orden en que se procesa cada nodo determina si el resultado es correcto.',
    81: 'Los BST se usan en bastantes rincones de la informática, en general para organizar y manejar datos de forma eficiente.',
    83: 'En sistemas de ⟦L⟧, la indexación es lo que mantiene rápidas las consultas. Un BST permite buscar en tiempo logarítmico, así que cada consulta necesita muchas menos comparaciones para encontrar un registro específico.',
    85: 'Cuando los datos tienen que mantenerse en un orden específico, un BST es una buena opción: permite insertar y eliminar sin romper esa estructura, algo importante cuando los datos cambian con frecuencia.',
    87: 'Manejar rangos de valores es una de las cosas que un BST hace mejor: encontrar todos los elementos dentro de un rango específico es rápido y directo.',
    89: 'Un BST también sirve de base para ⟦L⟧ más complejas: sumándole balanceo, como en AVL o rojo-negro, mantiene un rendimiento consistente sin importar cuántos datos maneje.',
    91: 'Medir la complejidad de un árbol es la única forma de saber si de verdad rinde. Y en un BST, ese rendimiento depende directamente de qué tan equilibrado esté.',
    93: 'Buscar, insertar y eliminar dependen de la altura del árbol. En uno equilibrado, cada operación corre en O(log n): el tiempo crece de forma logarítmica a medida que aumentan los nodos, que es justo lo que se busca.',
    95: 'El caso óptimo es un árbol perfectamente equilibrado. El peor caso aparece cuando los nodos se insertan ya ordenados (ascendente o descendente), degenerando el árbol en algo parecido a una lista, con operaciones que caen a O(n).',
    97: 'Los árboles balanceados, AVL o rojo-negro, mantienen su rendimiento porque su altura nunca supera O(log n). Los no balanceados no tienen esa garantía y pueden caer a O(n) en el peor caso.',
    99: 'Aplicar balanceo en cada inserción y eliminación es lo que mantiene la eficiencia del árbol a largo plazo, incluso con grandes volúmenes de datos.',
    101: 'Un BST no está libre de problemas típicos. Van algunos de los más comunes, con su solución.',
    103: 'Encontrar el segundo valor más grande se resuelve con un recorrido inorden desde la raíz: se van guardando los valores en orden ascendente hasta llegar al segundo más alto.',
    105: 'Sumar los primeros k valores menores también se resuelve con un recorrido inorden: como los valores llegan en orden ascendente, basta con sumar y llevar la cuenta hasta k, sin acumular nada de más.',
    107: 'Para balancear un BST existente, se recolectan todos sus elementos con un recorrido inorden y se reinsertan con un método que mantenga el equilibrio.',
    109: 'El sucesor de un nodo es el menor nodo mayor que él; el predecesor, el mayor nodo menor. Ambos se encuentran navegando desde el nodo objetivo por su subárbol derecho o izquierdo, según corresponda.',
    111: 'Un BST normalmente no admite duplicados, pero si hace falta manejarlos, una solución simple es guardar un contador por nodo que registre cuántas veces se insertó ese valor.',
    113: 'Para saber si dos árboles son iguales, se hace un recorrido simultáneo en ambos: comparar cada nodo en el camino valida su estructura y sus valores de forma eficiente.',
  },
  en: {
    0: "A ⟦L⟧ (BST) is one of the most fundamental structures in computer science for organizing data efficiently. Its design is what makes search, insertion, and deletion fast, which is why it shows up constantly when you're handling large volumes of data.",
    1: 'This guide covers the fundamentals of binary search tree in order traversal, the properties that make a BST work, and the core operations you need to actually use one well.',
    2: 'Binary search tree fundamentals',
    3: 'Definition and basic structure',
    4: "A binary search tree organizes nodes hierarchically, each with a unique value. Its search property is what makes it useful: every node in the left subtree holds a smaller value, every node in the right subtree holds a larger one. That single rule is why insertion, deletion, and search all average O(log n) in a balanced tree.",
    5: 'Essential node properties',
    6: "Every BST node needs at least three things: a value, a pointer to the left subtree, and a pointer to the right subtree. The value drives how the structure gets organized and searched. The pointers are what let you navigate between nodes cleanly, which matters for both search and traversal. Get these three right, and the rest of the tree's efficiency follows naturally.",
    7: 'Why ordering matters in a BST',
    8: "Ordering is what defines how you access and manipulate data in a BST. A properly balanced tree keeps search fast, and it also enables the binary search tree in order traversal, which returns every node's value in ascending order. That's useful anywhere you need sequential data, from processing logs to generating reports. Balance matters here too: without it, the tree degenerates into something like a linked list, and performance drops with it.",
    9: 'Core operations',
    10: 'A BST is useful because of four operations that modify and query it while preserving its search property: insertion, deletion, search, and traversal.',
    11: 'Inserting nodes',
    12: "Inserting a node is a recursive process: start at the root, compare the new value against the current node, go left if it's smaller and right if it's bigger, and repeat until you hit an empty spot. Average case is O(log n), though it can degrade to O(n) on an unbalanced tree.",
    13: 'Deleting nodes',
    14: 'Deletion gets more complicated depending on the node you are removing. There are three cases:',
    15: 'The node is a leaf: just remove it.',
    16: "The node has one child: remove it and connect that child directly to the deleted node's parent.",
    17: 'The node has two children: find the minimum node in the right subtree, copy its value into the node being deleted, then delete that minimum node.',
    18: 'Like insertion, deletion averages O(log n).',
    19: 'Searching for a value',
    20: 'Searching works the same way as inserting: start at the root and go left or right depending on the comparison, until you find the value or run out of tree. Average complexity is O(log n), degrading to O(n) if the tree is unbalanced.',
    21: 'Traversals',
    22: 'Traversals are how you process or visualize the data in a BST. The three common ones:',
    23: 'In order traversal: visits the left subtree, the current node, then the right subtree, producing values in ascending order.',
    24: 'Pre order traversal: visits the current node before its subtrees, useful for copying a tree.',
    25: 'Post order traversal: visits the current node after its subtrees, important when deleting a tree.',
    26: 'A binary search tree in order traversal always returns values in ascending order, which is exactly why it shows up so often in data analysis and everyday programming.',
    27: 'In order traversal and its variants',
    28: 'In order traversal is one of the most intuitive ways to walk a BST: left subtree, current node, right subtree, in that order. That pattern guarantees an ascending sequence of values, which is exactly what you want whenever an application needs sequential, sorted access to the data.',
    29: 'How in order traversal works',
    30: 'The algorithm starts at the root and moves all the way left first. Once it hits the smallest node, it processes that node and backtracks to explore the parent’s right subtree, repeating until every node has been visited. It runs in O(n), where n is the number of nodes, which makes it an efficient choice for this kind of ⟦L⟧.',
    31: 'Comparing with pre order and post order',
    32: "Pre order processes the current node before its subtrees, which is handy for copying a tree's structure or serializing it. Post order processes the subtrees first and the current node last, which is why it comes up in node deletion. Each variant has its place, but in order traversal is the one that hands you a sorted sequence for free, which is why it's the natural fit for visualizing data or evaluating a tree-structured math expression.",
    33: 'Practical applications',
    34: "In order traversal shows up across software development and data management. It's common in ⟦L⟧ where records need to come back in a specific order, and in ⟦L⟧ that need sorted data, like search algorithm implementations. File systems and other complex data structures also lean on it for fast, efficient access. Understanding this traversal is worth the time for any engineer working with data that needs to stay ordered and fast to retrieve.",
  },
}
