// Post 28 (graph-algorithms) rewritten block content.
// Index = position among heading/paragraph/listitem blocks in document order (per locale).
// Use ⟦L⟧ as a placeholder for each inline link node in that block, in order of appearance.
// Any index not present here means "keep original text unchanged" (used for clean headings).

export const post28: Record<'es' | 'en', Record<number, string>> = {
  es: {
    0: 'Los ⟦L⟧ de grafos son la base para modelar relaciones y resolver problemas complejos, así sea en redes sociales, logística o cualquier sistema donde los datos se conectan entre sí. En este artículo reviso la estructura y los tipos de grafos, sus algoritmos de recorrido, los caminos más cortos, los árboles de expansión mínima y el flujo máximo, y cierro con su implementación en Python.',
    2: 'Un grafo es una estructura formada por nodos y aristas: los nodos representan entidades y las aristas, las relaciones entre ellas. Con esa base se pueden modelar conexiones complejas, así sea en una red social o en un sistema de logística.',
    3: 'Cómo se clasifica un grafo determina qué ⟦L⟧ conviene usar para resolver cada problema.',
    4: 'Dirigidos y no dirigidos: en los dirigidos, cada arista apunta en un sentido específico, marcando el flujo entre dos nodos. En los no dirigidos la conexión es bidireccional, sin sentido fijo.',
    5: 'Ponderados y no ponderados: los ponderados asignan un valor numérico a cada arista (costo, distancia, tiempo). En los no ponderados todas las conexiones valen lo mismo.',
    6: 'Etiquetados y no etiquetados: en los etiquetados cada nodo tiene un identificador único. En los no etiquetados los nodos son indistinguibles entre sí.',
    7: 'Esta variedad es la que permite elegir el algoritmo correcto según el escenario, en vez de forzar una única solución para todos los casos.',
    9: 'Explorar un grafo significa recorrer sus nodos en un orden determinado para entender cómo se conectan. Los dos algoritmos que más se usan para esto son la Búsqueda en Profundidad (DFS) y la Búsqueda en Amplitud (BFS).',
    11: 'DFS avanza por un camino hasta llegar a un nodo sin salida y luego retrocede para probar otra ruta. Funciona bien para detectar ciclos o generar laberintos, donde hace falta un recorrido exhaustivo. Se puede implementar de forma recursiva o iterativa con una pila para guardar los nodos pendientes.',
    13: 'BFS, en cambio, avanza por capas: parte de un nodo inicial, revisa todos sus vecinos y solo después pasa al siguiente nivel. Por eso funciona bien para encontrar la ruta más corta en grafos no ponderados, y también para analizar redes sociales e identificar grupos de interacción.',
    15: 'Complejidad de tiempo: ambos corren en O(V + E), donde V es el número de nodos y E el de aristas.',
    16: 'Uso de memoria: DFS suele necesitar menos memoria que BFS, sobre todo en grafos muy ramificados.',
    17: 'Casos de uso: DFS conviene cuando quieres llegar rápido a un objetivo. BFS es mejor cuando necesitas la distancia mínima entre nodos.',
    18: 'Con estos dos algoritmos ya se puede responder casi cualquier pregunta básica sobre conectividad y recorrido en un grafo.',
    20: 'Encontrar el camino más corto en un grafo importa en casos muy distintos, así sea en la navegación GPS o en el diseño de redes. Hay varios algoritmos que resuelven este problema, cada uno con sus propias ventajas.',
    21: 'Dijkstra: encuentra la ruta más corta desde un nodo origen a todos los demás en un grafo ponderado. Mientras no haya pesos negativos, garantiza la solución óptima, y su eficiencia lo hace muy usado en enrutamiento y logística.',
    22: 'A*: parte del mismo principio que Dijkstra, pero suma una heurística que prioriza los caminos que parecen más cortos. Eso lo hace más rápido en videojuegos y sistemas de navegación que procesan datos en tiempo real.',
    23: 'Bellman-Ford: a diferencia de Dijkstra, sí soporta aristas con peso negativo. Es útil cuando hay "bonos" o descuentos en ciertos caminos, y también para detectar ciclos negativos.',
    24: 'Johnson: encuentra los caminos más cortos entre todos los pares de vértices en un grafo dirigido y ponderado. Repondera las aristas primero, lo que simplifica un problema que de otra forma sería mucho más pesado de calcular.',
    25: 'Elegir entre estos algoritmos no es solo un ejercicio teórico. En la práctica depende de la estructura del grafo y de lo que necesite la aplicación específica.',
    27: 'Un árbol de expansión mínima (MST) es el subconjunto de un grafo que conecta todos sus nodos al menor costo total posible. Se usa, entre otras cosas, para diseñar redes y planificar logística.',
    28: 'Los dos algoritmos más conocidos para esto son:',
    29: 'Prim: arranca en un nodo cualquiera y va sumando el más cercano que aún no está en el árbol. Funciona bien en grafos densos.',
    30: 'Kruskal: ordena todas las aristas del grafo y va seleccionando las más cortas, cuidando de no formar ciclos. Rinde mejor en grafos dispersos.',
    31: 'Cualquiera de los dos reduce el costo de instalar una red. En telecomunicaciones, por ejemplo, un MST optimiza el cableado necesario para conectar todas las estaciones.',
    32: 'Cuando la latencia mínima es la prioridad, la elección del algoritmo pesa directamente en el rendimiento de la red completa. Prim suele ser la opción cuando hace falta una solución rápida y directa.',
    33: 'Kruskal, en cambio, se desempeña mejor cuando hay que gestionar varios componentes desconectados, sumando conexiones de forma progresiva sin complicarse.',
    34: 'En la práctica, usar estos algoritmos ahorra costos y deja una infraestructura con conexiones efectivas entre los nodos.',
    36: 'Los algoritmos de flujo máximo se usan para planificar recursos, diseñar redes y optimizar procesos industriales. Su objetivo es calcular cuánto flujo puede enviarse a través de una red modelada como nodos y conexiones.',
    37: 'Ford-Fulkerson es el método más conocido para resolver flujo máximo. Busca caminos de aumento en la red donde todavía se puede meter más flujo, y se puede implementar con DFS o BFS según el contexto.',
    38: 'Dinic mejora la eficiencia de Ford-Fulkerson con una búsqueda por niveles: divide la red en capas y encuentra flujos a través de ellas, lo que reduce el tiempo de ejecución en redes densas.',
    39: 'Un punto que vale la pena vigilar es la detección de ciclos: en redes con retroalimentación hace falta manejarlos con técnicas específicas o el resultado sale ineficiente o directamente erróneo. Una lista de adyacencia suele bastar para gestionar estos casos.',
    40: 'Ford-Fulkerson: el enfoque clásico para resolver flujo máximo.',
    41: 'Dinic: mejora la eficiencia con búsqueda por niveles.',
    42: 'Detección de ciclos: imprescindible en redes con retroalimentación.',
    43: 'Estos algoritmos tienen ⟦L⟧ en logística, donde optimizar rutas depende de gestionar bien los flujos, y en telecomunicaciones, donde el objetivo es maximizar la capacidad de transmisión entre nodos.',
    45: 'El coloreo de grafos consiste en asignar colores a los nodos de forma que dos nodos adyacentes nunca compartan color. Se aplica en asignación de recursos, planificación de horarios y compresión de datos.',
    46: 'El algoritmo de Welsh-Powell es uno de los más usados: ordena los nodos por grado decreciente y va asignando colores mientras respeta la restricción con los nodos adyacentes. Como el problema es NP-completo en su forma general, en la práctica se recurre a heurísticas para llegar a soluciones buenas, aunque no siempre óptimas.',
    47: 'La detección de comunidades busca algo distinto: identificar grupos de nodos más conectados entre sí que con el resto del grafo. Es clave para entender cómo se forman las interacciones dentro de una red social.',
    48: 'Louvain: maximiza la modularidad de la estructura del grafo para identificar comunidades.',
    49: 'Infomap: usa teoría de la información para detectar comunidades, minimizando la descripción de los movimientos aleatorios dentro del grafo.',
    50: 'Girvan-Newman: detecta comunidades eliminando progresivamente las aristas de mayor centralidad.',
    51: 'Estos métodos se usan en redes sociales, pero también en biología, análisis de redes de comunicación y detección de fraude. La investigación en este campo sigue buscando más precisión y eficiencia para detectar patrones en grafos complejos.',
    53: 'Python es el lenguaje que más se usa para implementar algoritmos de grafos, por su sintaxis simple y sus bibliotecas. Las más populares son NetworkX y graph-tool, que ya traen ⟦L⟧ y funciones listas para trabajar con grafos.',
    54: 'NetworkX es un buen punto de partida para experimentar con algoritmos de grafos: permite crear, manipular y estudiar la estructura y dinámica de una red, tiene documentación completa y se instala fácil con pip. Los pasos básicos para armar un grafo son:',
    55: 'Instalación: pip install networkx',
    56: 'Importación de la biblioteca: import networkx as nx',
    57: 'Creación de un grafo: G = nx.Graph()',
    58: 'Adición de nodos y aristas: G.add_node(1) y G.add_edge(1, 2)',
    59: 'Para correr DFS o BFS, NetworkX ya trae funciones integradas que simplifican el proceso. Por ejemplo, una búsqueda en amplitud desde un nodo fuente se ejecuta con:',
    61: 'Correr Dijkstra también es directo: basta con definir un grafo ponderado y usar la función que trae NetworkX para calcular la ruta óptima entre dos nodos.',
    62: 'Graph-tool es menos común, pero es una opción robusta para análisis complejos gracias a su enfoque en eficiencia. Rinde mejor con grandes volúmenes de datos, aunque instalarlo cuesta más por sus dependencias.',
    63: 'Implementar estos algoritmos en Python no solo ayuda a aprenderlos: también permite aplicarlos a problemas reales, adaptados a las ⟦L⟧ de cada caso.',
  },
  en: {
    0: 'Graph algorithms solve a wide range of problems across computer science and math. This guide walks through the fundamentals of graph theory, covering definitions, components, and where each one actually gets used.',
    1: "From traversal to shortest paths to minimum spanning trees, each section gives developers and technical practitioners what they need to put these tools to work.",
    3: "Graph theory is the branch of computer science and math that models pairwise relationships between objects. A graph is just vertices (nodes) and edges (connections) between them. Once you have that, you can start exploring the algorithms that operate on these structures, whether it's network design or social media analysis.",
    5: 'A graph is a set of vertices V and a set of edges E, where each edge connects two vertices and represents a relationship between them. Graphs can be directed, where each edge has a one-way direction, or undirected, where the relationship goes both ways. Getting these basics right matters before you implement any graph algorithm.',
    7: "Graphs get classified by a few key attributes. Directed graphs handle one-way relationships, which fits scenarios like web page linking. Undirected graphs represent mutual relationships instead. Separately, a graph can be weighted or unweighted: weighted graphs attach a value to each edge, whether that's cost, distance, or some other metric, while unweighted graphs treat every connection the same. Which type you're dealing with shapes which algorithm actually makes sense.",
    9: 'How you represent a graph in memory matters too. The two most common ways are adjacency lists and adjacency matrices. An adjacency list keeps a list per vertex of everything it connects to, which is memory-efficient for sparse graphs. An adjacency matrix uses a 2D array to mark which vertex pairs are adjacent, which gives faster lookups at the cost of more memory. Picking the right one changes how well a given algorithm actually performs.',
    10: 'Once these fundamentals click, applying graph algorithms to real problems gets a lot easier, no matter the field.',
    12: "Traversal algorithms let you systematically explore a graph's nodes and edges. The two fundamental approaches are Breadth-First Search (BFS) and Depth-First Search (DFS), each with its own strengths depending on what you're trying to solve.",
    14: "BFS explores a graph level by level. Starting from a root node, it visits every adjacent node before moving to the next level, so all nodes at a given depth get explored before anything deeper. It relies on a queue ⟦L⟧ to track what's pending and marks nodes as visited once processed. It's the go-to for finding the shortest path in unweighted graphs and for exploring routes in network routing.",
    16: "DFS takes the opposite approach: it goes as far down one branch as it can before backtracking. It uses a stack, either explicit or through recursion, to keep track of where it's been. When it hits a dead end, it backs up and tries another branch. That makes it a good fit for exploring every possible configuration, whether it's solving a puzzle or navigating a maze, and it can also detect cycles.",
    18: "BFS and DFS show up everywhere because they're efficient and flexible. A few concrete applications:",
    19: 'Routing protocols that find optimal paths for data packets (BFS).',
    20: 'Search engine crawlers that index and explore the web (BFS).',
    21: 'Puzzles like the sliding tile game and maze navigation (DFS).',
    22: 'Social network analysis, identifying clusters and communities (BFS and DFS).',
    23: 'Checking network connectivity to find isolated nodes (DFS).',
    24: "Both algorithms are foundational for anyone working with complex data structures, and their reach goes well beyond computer networks, all the way into artificial intelligence.",
    26: "Shortest path algorithms find the most efficient route between two nodes in a graph, whether that's for networking, transportation, or AI. Here are the algorithms that come up most often, and what each one is actually good for.",
    28: "Dijkstra's is the algorithm most people reach for first. It works on weighted graphs with non-negative edge weights, sets the source node's distance to zero and everything else to infinity, then repeatedly picks the nearest unvisited node and updates its neighbors' distances. It's a natural fit for routing protocols and geographical mapping, where accurate distances actually matter.",
    29: 'A* Algorithm',
    30: "A* builds on Dijkstra by adding a heuristic to the search. Its cost function combines the distance already traveled with an estimated cost to the goal, which usually gets you to a good path faster. That's why it shows up so often in gaming and robotics, where you need both an optimal path and a real-time answer.",
    32: "Bellman-Ford handles something Dijkstra can't: negative edge weights, which come up in currency exchange calculations and similar cases. It relaxes every edge repeatedly until the shortest paths settle. It's slower than Dijkstra when there are no negative weights, but that tolerance for negative cycles makes it worth keeping around.",
    34: "Johnson's algorithm finds shortest paths between every pair of vertices, handling positive and negative weights alike. It reweights the graph to remove the negative weights, then just runs Dijkstra, which ends up a lot cheaper than the direct alternatives. It works particularly well on sparse graphs.",
    35: 'Comparison of Shortest Path Algorithms',
    36: 'Picking the right shortest path algorithm comes down to graph density, edge weights, and what the application actually needs. The table below lays out how they compare.',
    38: "A minimum spanning tree connects every vertex in a graph at the lowest total edge weight possible, which is exactly what you want for network design, optimization, or cluster analysis. The two algorithms everyone reaches for are Kruskal's and Prim's, and they get there in different ways.",
    40: "Kruskal's sorts every edge by weight, ascending, then adds edges one at a time to the growing tree as long as they don't form a cycle. A disjoint-set data structure keeps track of which vertices belong to which component. The steps look like this:",
    44: "Kruskal's shines on sparse graphs, where there are far fewer edges than the maximum possible, which keeps the computation fast.",
    46: "Prim's takes a different route: start from any vertex and grow the tree one edge at a time, always adding the lowest-weight edge that connects the tree to a vertex still outside it. Repeat until every vertex is in. The basic steps:",
    50: "Prim's tends to do better on dense graphs, since it can take advantage of how connected everything already is.",
    52: 'MSTs show up in plenty of real applications. A few worth knowing:',
    53: 'Network design: laying out telecom and computer networks with the least cabling cost possible.',
    54: 'Clustering: grouping data points in machine learning to minimize the distance between clusters.',
    55: 'Transportation: designing efficient routes for logistics networks.',
    56: 'Image processing: compressing images while keeping the information that matters, by modeling pixel connections.',
    57: "That efficiency is exactly why MST algorithms keep showing up in real systems, and why it's worth understanding graph theory beyond the textbook definitions.",
    59: "Flow and connectivity algorithms deal with how things move through a graph and how connected it actually is, whether it's a transportation network, resource allocation, or network design.",
    61: "Maximum flow algorithms figure out the greatest flow you can push from a source to a sink without exceeding any edge's capacity. Ford-Fulkerson is the classic method: it greedily finds augmenting paths and keeps increasing the flow along them until none are left.",
    62: 'Edmonds-Karp is Ford-Fulkerson with BFS used to find those augmenting paths, which guarantees the shortest ones get picked first and lands you at a ⟦L⟧ of O(VE²). Maximum flow shows up in telecommunications, logistics, and project management.',
    64: 'Connected components are the subgraphs where every pair of vertices has a path between them. Finding them usually just means running DFS or BFS, marking nodes as visited and tracking which component each one falls into.',
    65: 'This matters for social network analysis, clustering, and graphical data representation. Understanding connectivity also helps you gauge network resilience, spot vulnerabilities, and optimize communication paths.',
    67: "Detecting cycles matters whenever you need to understand a network's structure. The approach depends on whether the graph is directed or undirected. For undirected graphs, DFS works: if you hit a node you've already visited and it isn't the direct parent of the current node, there's a cycle.",
    68: 'For directed graphs, you track a recursion stack to spot back edges, and a back edge means there is a cycle. This comes up in deadlock detection in operating systems, validating DAGs, and scheduling project workflows.',
    69: 'Between maximum flow, connected components, and cycle detection, this group of algorithms covers a big chunk of what graph theory is actually used for in practice.',
    71: 'Beyond the standard traversal and pathfinding methods, a handful of specialized algorithms solve narrower, more specific problems.',
    73: "An Eulerian path visits every edge in a graph exactly once. An Eulerian circuit does the same but ends back where it started. Fleury's algorithm finds either one with a simple rule: avoid bridges (edges that would split the graph into more components if removed) unless there's no other option. That keeps the resulting path valid.",
    80: 'It is practical for routing problems like garbage collection or street cleaning routes, where the goal is covering every area while minimizing travel.',
    82: "Topological sorting lines up the vertices of a directed acyclic graph (DAG) so that for every edge from A to B, A comes first. It's what makes task scheduling work when some tasks have to happen before others. You can implement it with DFS or with Kahn's algorithm.",
    83: 'Project management and scheduling tools rely on it to respect task dependencies, and compilers use the same idea to build files in the right order.',
    85: 'Graph coloring assigns colors to vertices so no two adjacent ones share a color. It is most useful in scheduling and resource allocation, anywhere conflicts need to be avoided. The chromatic number, the minimum colors a proper coloring needs, is the number that matters most here.',
    86: 'Scheduling problems: assigning time slots or resources to tasks without conflicts.',
    87: 'Register allocation: assigning a limited set of registers to variables during compilation.',
    88: 'Map coloring: making sure no two adjacent regions on a map share a color.',
    89: 'Graph coloring is worth knowing if you work on optimization problems at all. It is a clean example of how constraints shape the solution space in practice.',
  },
}
