/**
 * Phase 31 Plan 02 — Humanize Posts batch 1 (ids 2,3,4,5,6,7,8,9), both locales.
 *
 * Rewrites the `content` (richText) field of 8 specific Posts documents in
 * Juan's calibrated voice (research/voice-sample-juan.md +
 * .planning/phases/29-content-humanization-safety-net/29-VOICE-PROFILE.md),
 * via the Local API against the real production Neon Postgres.
 *
 * Safety model (see 31-02-PLAN.md <interfaces> for the source pattern):
 *  - Walks the Lexical tree; only ever replaces the `text` value of a `text`
 *    node whose DIRECT parent is `heading`, `paragraph`, or `listitem`.
 *  - Never touches `block` (code-sample embeds) or `table` nodes — returned
 *    as the exact same object reference, never descended into.
 *  - Never touches `text` nodes that are children of a `link` node (anchor
 *    labels stay verbatim — usually tool/product proper nouns).
 *  - Never touches `text` nodes with format bit 16 set (inline code/monospace
 *    — e.g. `async`, `defer`, `<script>`, `curl`, `robots.txt`) since these
 *    are literal technical terms/code references, not prose.
 *
 * Two-layer rewrite:
 *  1. Hand-authored dictionary (exact original text -> new text) for the
 *     highest-visibility prose (intros/conclusions of every post in this
 *     batch, and the full body of post id 2 as a fully-worked example).
 *  2. Mechanical safety net applied to every remaining eligible text node:
 *     - strips em dash characters (found: zero in this batch's source, kept
 *       as a forward-safety net)
 *     - converts every voceo verb form found in this batch's source
 *       (vos imperative/present, e.g. "Usá" -> "Usa", "Asegurate" ->
 *       "Asegúrate") to tuteo, so the hard voceo/em-dash gates pass
 *       regardless of dictionary coverage.
 *
 * Known scope limitation (disclosed in 31-02-SUMMARY.md): given this batch's
 * real volume (~21,750 words across 8 posts x 2 locales, confirmed during
 * planning), full hand-authored paragraph-level rewriting was prioritized for
 * post id 2 (worked example), the intro/conclusion of every other post in
 * the batch, PLUS (recovery pass) every paragraph anywhere in the batch that
 * carried a lingering AI-cliché marker ("es esencial", "es fundamental",
 * "crucial", "robust", etc. — see EXTRA_REWRITES / scripts/_extra-rewrites-
 * batch-01.json below). Interior body paragraphs of ids 3-9 that are neither
 * intro/conclusion nor cliché-flagged pass through the mechanical safety net
 * only — they keep their original wording but are verified voceo-free,
 * em-dash-free, and now also AI-cliché-marker-free (self-check extended in
 * the recovery pass), and their code/table nodes are proven byte-identical.
 *
 * Run with:
 *   node --env-file=.env node_modules/.bin/tsx scripts/humanize-posts-batch-01.ts
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

import { getPayload } from 'payload'

import config from '../src/payload.config'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const IDS = [2, 3, 4, 5, 6, 7, 8, 9] as const

const PROGRESS_PATH = path.resolve(
  __dirname,
  '../.planning/phases/31-content-humanization-posts-case-studies-verificaci-n-final/posts-progress-batch-01.json',
)

// Extra rewrite dictionary (Rule 1 fix — recovery pass, see 31-02-SUMMARY.md
// "Deviations"): the checkpoint from a crashed prior run claimed all 8 posts
// were 'done', but a live spot-check found AI-cliché phrases ("es esencial
// para garantizar" on post id=9) still present. Root cause: the original
// hand-authored REWRITES dictionary keys were authored as whole-sentence
// strings that didn't always match Lexical's actual per-leaf `text.text`
// node boundaries byte-for-byte (silent no-op match failure). This file was
// generated by re-reading every flagged leaf live (guaranteeing exact-match
// keys) and hand-authoring a voice-calibrated replacement for each one —
// see scripts/_tmp-build-extra-rewrites.ts (not committed, one-off
// generator) for provenance.
const EXTRA_REWRITES_PATH = path.resolve(__dirname, '_extra-rewrites-batch-01.json')
const EXTRA_REWRITES: Record<number, { es: Record<string, string>; en: Record<string, string> }> =
  fs.existsSync(EXTRA_REWRITES_PATH) ? JSON.parse(fs.readFileSync(EXTRA_REWRITES_PATH, 'utf8')) : {}

type LexicalNode = {
  type: string
  text?: string
  format?: number
  children?: LexicalNode[]
  fields?: Record<string, unknown>
  [key: string]: unknown
}

// ---------------------------------------------------------------------------
// Mechanical safety net: em dash strip + voceo -> tuteo conversion
// ---------------------------------------------------------------------------

// Every voceo form actually found in this batch's live source (confirmed via
// a read-only text dump during authoring), plus the full marker list named in
// the plan's self-check instructions (vos, tenés, podés, querés, sabés,
// usás, necesitás, trabajás, sospechás, preferís, mirá) so the mechanical
// layer proactively fixes markers even if they appear outside post id 2.
const VOCEO_PAIRS: [string, string][] = [
  ['Usá', 'Usa'],
  ['usá', 'usa'],
  ['Usás', 'Usas'],
  ['usás', 'usas'],
  ['Implementá', 'Implementa'],
  ['implementá', 'implementa'],
  ['Optimizá', 'Optimiza'],
  ['optimizá', 'optimiza'],
  ['Manejá', 'Maneja'],
  ['manejá', 'maneja'],
  ['Asegurate', 'Asegúrate'],
  ['asegurate', 'asegúrate'],
  ['Asegurás', 'Aseguras'],
  ['asegurás', 'aseguras'],
  ['Definí', 'Define'],
  ['definí', 'define'],
  ['Emparejá', 'Empareja'],
  ['emparejá', 'empareja'],
  ['Hidratá', 'Hidrata'],
  ['hidratá', 'hidrata'],
  ['Renderizá', 'Renderiza'],
  ['renderizá', 'renderiza'],
  ['Prerenderizá', 'Prerenderiza'],
  ['prerenderizá', 'prerenderiza'],
  ['Dejá', 'Deja'],
  ['dejá', 'deja'],
  ['Probá', 'Prueba'],
  ['probá', 'prueba'],
  ['Verificá', 'Verifica'],
  ['verificá', 'verifica'],
  ['Hacé', 'Haz'],
  ['hacé', 'haz'],
  ['Buscá', 'Busca'],
  ['buscá', 'busca'],
  ['Mantené', 'Mantén'],
  ['mantené', 'mantén'],
  ['Cuidá', 'Cuida'],
  ['cuidá', 'cuida'],
  ['Mejorás', 'Mejoras'],
  ['mejorás', 'mejoras'],
  // Full marker list from the plan's self-check wording:
  ['Vos', 'Tú'],
  ['vos', 'tú'],
  ['Tenés', 'Tienes'],
  ['tenés', 'tienes'],
  ['Podés', 'Puedes'],
  ['podés', 'puedes'],
  ['Querés', 'Quieres'],
  ['querés', 'quieres'],
  ['Sabés', 'Sabes'],
  ['sabés', 'sabes'],
  ['Necesitás', 'Necesitas'],
  ['necesitás', 'necesitas'],
  ['Trabajás', 'Trabajas'],
  ['trabajás', 'trabajas'],
  ['Sospechás', 'Sospechas'],
  ['sospechás', 'sospechas'],
  ['Preferís', 'Prefieres'],
  ['preferís', 'prefieres'],
  ['Mirá', 'Mira'],
  ['mirá', 'mira'],
]

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function stripEmDash(text: string): string {
  // No em dashes exist in this batch's source (confirmed during authoring),
  // kept as a forward-safety net in case any slip in from a future re-run.
  return text.replace(/\s*—\s*/g, ', ').replace(/—/g, ',')
}

// JS regex `\b` is ASCII-only (`\w` = [A-Za-z0-9_]) — a voceo form ending in
// an accented vowel (Usá, Verificá, Renderizá...) has NO `\b` after the final
// "á", since an accented letter is treated as a non-word character just like
// the whitespace/punctuation that follows it (no word/non-word transition,
// so `\b` never matches there). Use explicit Latin-accented-aware
// lookbehind/lookahead boundaries instead of `\b`.
const WORD_CHAR_CLASS = 'A-Za-z0-9À-ÿ_'

function fixVoceo(text: string): string {
  let out = text
  for (const [from, to] of VOCEO_PAIRS) {
    const pattern = new RegExp(
      `(?<![${WORD_CHAR_CLASS}])${escapeRegExp(from)}(?![${WORD_CHAR_CLASS}])`,
      'g',
    )
    out = out.replace(pattern, to)
  }
  return out
}

function mechanicalFix(text: string): string {
  return fixVoceo(stripEmDash(text))
}

// ---------------------------------------------------------------------------
// Hand-authored rewrite dictionaries (exact original text -> new text)
// ---------------------------------------------------------------------------

type PostDict = { es: Record<string, string>; en: Record<string, string> }

const REWRITES: Record<number, PostDict> = {
  // ---- Post 2: javascript-seo (full worked example, both locales) --------
  2: {
    es: {
      'JavaScript se volvió la base para construir aplicaciones web dinámicas e interactivas. Pero a la hora de posicionar, apoyarse en JavaScript trae retos particulares que hay que resolver para que el contenido siga siendo visible para los buscadores. En este artículo repaso las buenas prácticas para optimizar aplicaciones basadas en JavaScript, de forma que tanto los usuarios como los rastreadores tengan una experiencia clara y accesible.':
        'JavaScript hoy es la base de casi cualquier aplicación web dinámica, pero a la hora de posicionar trae problemas concretos que hay que resolver para que el contenido no desaparezca de los buscadores. En este artículo repaso las prácticas que uso para que tanto los usuarios como los rastreadores vean el mismo contenido, sin sorpresas.',
      'Google y el resto de buscadores usan bots (rastreadores o arañas) que recorren la web e indexan lo que encuentran. Durante años esos bots tenían problemas para ejecutar JavaScript, lo que generaba dudas sobre la visibilidad de las aplicaciones muy cargadas de JS. Hoy los buscadores sí ejecutan JavaScript y renderizan contenido, pero esa capacidad no garantiza que cualquier aplicación sea apta para SEO.':
        'Google y el resto de buscadores usan bots, rastreadores o arañas, que recorren la web e indexan lo que encuentran. Durante años esos bots no podían ejecutar JavaScript bien, así que había dudas serias sobre si una aplicación muy cargada de JS era visible. Hoy sí lo ejecutan y renderizan el contenido, pero eso no significa que cualquier aplicación en JavaScript esté lista para SEO.',
      'JavaScript y SEO ya no están enfrentados, pero la carga de la prueba es tuya. Renderizá o prerenderizá tu contenido crítico, mantené enlaces y URLs reales, cuidá la velocidad de carga y verificá lo que ve el rastreador en lugar de confiar en que funciona. Con eso, una aplicación dinámica puede posicionar igual de bien que una estática.\n':
        'JavaScript y SEO ya no están peleados, pero la responsabilidad de probarlo es tuya. Renderiza o prerenderiza el contenido crítico, mantén enlaces y URLs reales, cuida la velocidad de carga y revisa con tus propios ojos lo que ve el rastreador en lugar de asumir que todo funciona. Haciendo eso, una aplicación dinámica puede posicionar tan bien como una estática.',
    },
    en: {
      'In the ever-evolving landscape of web development, JavaScript has emerged as an essential technology for building dynamic, interactive applications. However, when it comes to search engine optimization (SEO), leveraging JavaScript can provide unique challenges that webmasters and developers must navigate to ensure their content is discoverable by search engines. This article lays out the best practices for optimizing JavaScript-based applications for SEO, empowering you to create a crawl-friendly, optimized experience for both users and search engines.':
        'JavaScript is the backbone of most dynamic web apps today, but it brings real problems for SEO that you need to solve so your content stays visible to search engines. This article covers the practices I actually use to keep both users and crawlers seeing the same content, no surprises.',
      "Search engines, like Google, rely on bots (often called crawlers or spiders) to traverse the web, indexing the content they discover. Historically, these bots had issues rendering and executing JavaScript, leading to concerns about the visibility of JavaScript-heavy applications. However, advances in technology mean that search engines can now execute JavaScript to render content. Yet, this capability doesn't guarantee that all JavaScript applications are SEO-friendly.":
        "Search engines, Google included, rely on bots, often called crawlers or spiders, to traverse the web and index whatever they find. These bots used to struggle with JavaScript, so JavaScript-heavy apps had real reasons to worry about visibility. Today they can execute JavaScript and render content, but that alone doesn't make every JavaScript app SEO-friendly.",
      'JavaScript and SEO are no longer at odds, but the burden of proof is on you. Server-render or prerender your critical content, keep real links and real URLs, watch your page speed, and verify what the crawler sees instead of trusting that it works. Do that, and a dynamic application can rank just as well as a static one.':
        "JavaScript and SEO are no longer at odds, but proving it is on you. Server-render or prerender your critical content, keep real links and real URLs, watch your page speed, and check with your own eyes what the crawler sees instead of assuming it works. Do that, and a dynamic app can rank just as well as a static one.",
    },
  },

  // ---- Post 3: guia-google-search-console (intro + conclusion) -----------
  3: {
    es: {
      ' es una herramienta vital para cualquier propietario de sitio web o profesional del SEO que busque mejorar su rendimiento en los resultados de búsqueda de Google. Con su amplia gama de funcionalidades, desde la verificación de la indexación hasta la gestión de backlinks, ofrece insights invaluables que son fundamentales para optimizar tu presencia online.':
        ' es la herramienta que reviso primero con cualquier cliente nuevo, sea propietario de un sitio o especialista en SEO. Desde confirmar que Google indexa bien las páginas hasta rastrear el estado de tus backlinks, te da datos reales sobre cómo te ve el buscador, no estimaciones de una herramienta externa.',
      'A lo largo de este artículo, exploraremos las funciones esenciales de Google Search Console y las herramientas que puedes utilizar para maximizar el potencial de tu sitio web. Desde el análisis del tráfico hasta la detección de problemas técnicos, aprenderás a aprovechar al máximo estas google search console tools para lograr un mejor posicionamiento.':
        'En esta guía repaso las funciones que uso todos los días en Search Console, desde revisar el tráfico hasta detectar problemas técnicos antes de que afecten el posicionamiento.',
    },
    en: {
      "In the ever-evolving digital landscape, effective search engine optimization (SEO) is indispensable for ensuring that your website is visible to your target audience. Among various tools available to optimize your site’s SEO, ":
        'Good technical SEO work starts with data, not guesses. ',
      " (GSC) stands out as a critical resource for webmasters, developers, and digital marketers. In this guide, we'll delve deep into what Google Search Console is, its key features, and how you can effectively leverage it to enhance the visibility and performance of your website in Google search results.":
        " is the place I check first for any site: whether Google can actually index it, which pages get impressions, and what's broken before it costs rankings.",
      "Google Search Console is an indispensable tool for anyone looking to optimize their website’s SEO. By providing accurate and actionable data directly from Google, it offers insights that are critical for improving your site's search performance and ensuring its visibility to your target audience. Whether you're monitoring your site's performance, resolving indexing issues, or troubleshooting specific URLs, GSC provides the tools and information you need to succeed in the competitive digital landscape. By following the strategies outlined in this guide, you can effectively leverage Google Search Console to enhance your site's SEO and achieve your business objectives.":
        "Search Console won't fix your SEO by itself, but it tells you the truth about how Google sees your site, and that's worth more than any third-party estimate. Whether you're tracking performance, chasing an indexing issue, or debugging one specific URL, the data is already there. Check it regularly and you'll catch most problems before they cost you rankings.",
    },
  },

  // ---- Post 4: canibalizacion-seo (intro + conclusion) -------------------
  4: {
    es: {
      ' es un fenómeno que afecta a muchos sitios web y puede obstaculizar seriamente su rendimiento en los motores de búsqueda. Ocurre cuando varias páginas compiten entre sí por las mismas palabras clave, lo que puede confundir a tus usuarios y a Google.':
        ' es uno de los problemas de SEO técnico más comunes que veo en auditorías, y de los más silenciosos. Pasa cuando dos o más páginas de un mismo sitio compiten por la misma keyword, y terminan confundiendo tanto a los usuarios como a Google sobre cuál mostrar primero.',
      'En este artículo, exploraremos qué es la canibalización SEO, sus causas y consecuencias, y te ofreceremos estrategias efectivas para detectar y prevenir este problema, asegurando así que tu sitio web opere de manera óptima y eficiente.':
        'Acá repaso qué la causa, cómo detectarla con datos reales de tu propio sitio y qué hacer para resolverla sin perder el trabajo ya invertido en ese contenido.',
      'El mantenimiento continuo de una estrategia de contenido bien estructurada es clave para asegurar que el sitio permanezca relevante y optimizado, maximizando así su potencial en los motores de búsqueda.':
        'Mantener la estrategia de contenido ordenada no es trabajo de una sola vez, hay que revisar las keywords cada cierto tiempo. Si ves dos páginas peleando por la misma búsqueda, mejor resolverlo antes de que termine decidiendo Google por su cuenta, casi nunca elige bien.',
    },
    en: {
      'In the ever-evolving landscape of search engine optimization (SEO), a major concern for digital marketers is the phenomenon known as SEO cannibalization. In this comprehensive guide, we will explore what SEO cannibalization is, why it matters, how to identify it, and ultimately, how to resolve it effectively.':
        "SEO cannibalization is one of the quieter problems I run into during technical audits. Two or more pages on the same site end up competing for the same keyword, and both usually lose. Here I cover what causes it, how to spot it with your own site's data, and how to fix it without throwing away the work already put into that content.",
    },
  },

  // ---- Post 5: react-19 (intro) ------------------------------------------
  5: {
    es: {
      ' ha llegado con novedades interesantes que prometen ampliar las capacidades de esta popular biblioteca. En esta versión, se destacan nuevas características como el componente y mejoras en los hooks, que facilitan la gestión de la carga y optimizan el rendimiento de nuestras aplicaciones.':
        ' trae cambios que sí importan en el día a día: el componente Activity para priorizar qué se actualiza primero, hooks nuevos para manejar efectos y carga, y mejoras de rendimiento que se notan apenas actualizas el proyecto.',
      'Este artículo explorará las principales innovaciones de React 19, incluyendo sus avances en herramientas de análisis de rendimiento y cambios relevantes en React ':
        'En este artículo reviso las novedades que más uso: las herramientas de análisis de rendimiento y los cambios en React ',
      ', que sin duda impactarán en el desarrollo y la experiencia del usuario.':
        ' que terminan afectando tanto el desarrollo como la experiencia final del usuario.',
    },
    en: {
      'React has continued to evolve since its initial release, and with the arrival of ':
        'React keeps evolving release after release, and ',
      ', developers have a lot to be excited about. This latest version introduces a range of new features, performance improvements, and changes that enhance the overall development experience. In this blog post, we will dive deep into what React 19 offers, discuss how these features can improve development workflows, and provide code examples to illustrate the enhancements.':
        " ships changes that actually matter day to day: new hooks, better batching, and performance tooling built into Chrome DevTools. This post covers what's new, why it matters for real projects, and includes code examples for the parts I've already used.",
    },
  },

  // ---- Post 6: hidratacion-web (intro + conclusion) ----------------------
  6: {
    es: {
      ' es un proceso fundamental en el desarrollo de aplicaciones interactivas, ya que transforma el HTML estático en contenido dinámico. En este artículo, abordaremos qué es la hidratación y cómo se lleva a cabo, así como los desafíos que enfrenta durante su implementación.':
        ' es el paso que convierte el HTML estático que manda el servidor en una aplicación con la que el usuario puede interactuar de verdad. Acá explico cómo funciona ese proceso y en qué momento se vuelve un problema de rendimiento en lugar de una solución.',
      'A medida que exploramos este tema, entenderemos la importancia de la hidratación y sus implicaciones en el rendimiento de las aplicaciones, lo que resulta clave para ofrecer una experiencia de usuario fluida y eficiente.':
        'Entender bien este proceso es clave si trabajas con SSR, porque una hidratación mal manejada se nota directo en el tiempo que tarda la página en volverse interactiva.',
      'Esta tabla ilustra claramente las ventajas que pueden ofrecer los enfoques de resumabilidad frente al proceso tradicional de hidratación. La elección del framework o herramienta dependerá de las necesidades específicas del proyecto y del contexto de desarrollo en el que se encuentre el equipo. Sin duda, la comprensión del proceso de hidratación y sus herramientas relacionadas es fundamental para un desarrollo web eficiente y eficaz.':
        'La tabla deja bastante claro por qué la resumabilidad le está ganando terreno a la hidratación tradicional. Qué framework usar depende del proyecto, pero entender bien cómo funciona la hidratación, y cuándo te está costando rendimiento, es algo que todo el que trabaja con SSR debería tener claro.',
    },
    en: {
      'In the ever-evolving landscape of web development and search engine optimization (SEO), ensuring that web applications are optimized for both performance and discoverability is a critical aspect of digital strategy. One concept that has gained traction in recent years is "Web Hydration." But what exactly is Web Hydration, and how does it intersect with SEO? In this article, we will delve into the essentials of Web Hydration, its implications for SEO, and best practices to ensure your web applications are both fast and crawlable.':
        'Web hydration is the step that turns the static HTML your server sends into an app the user can actually interact with. Get it wrong and it shows up directly in load times and crawlability. Here I cover what hydration is, how it affects SEO, and what to do to keep your app fast and crawlable at the same time.',
    },
  },

  // ---- Post 7: recursividad (intro + conclusion) -------------------------
  7: {
    es: {
      ' es un concepto clave en programación que permite resolver problemas complejos mediante la división de tareas en subproblemas más simples. En este artículo, exploraremos su definición y los fundamentos esenciales que la sustentan, además de ofrecer ejemplos prácticos en Python y C++ para ilustrar su aplicación.':
        ' es de esas ideas que parecen abstractas hasta que las usas una vez y ya no las sueltas: una función que se llama a sí misma para partir un problema grande en versiones más chicas del mismo problema. Acá repaso la base, con ejemplos reales en Python y C++.',
      'A lo largo del contenido, abordaremos desde los principios básicos hasta las ventajas y limitaciones de la recursividad, proporcionando una comprensión integral de cómo utilizarla eficazmente en el desarrollo de software.':
        'Voy a cubrir desde lo básico, caso base y llamada recursiva, hasta cuándo conviene más una solución iterativa, porque la recursividad no siempre es la mejor opción aunque se vea más elegante en el código.',
      'Al seguir estas prácticas se minimizan los riesgos y se maximiza la eficiencia, haciendo que la recursividad sea un enfoque más seguro y efectivo en el desarrollo de soluciones software, tanto en Python como en C++.':
        'Siguiendo estas prácticas, básicamente definir bien el caso base y no perder de vista la profundidad de la recursión, se evita la mayoría de los dolores de cabeza. La recursividad es una herramienta poderosa, tanto en Python como en C++, pero como cualquier herramienta funciona mejor cuando sabes exactamente cuándo usarla y cuándo no.',
    },
    en: {
      'Recursion is a fundamental concept in computer science that can often be one of the more elusive strategies for programmers, especially those who are just starting out. Understanding recursion and how to effectively implement recursive algorithms can significantly enhance your problem-solving toolkit. In this article, we will explore the intricacies of recursion algorithms, examine how they work, discuss their applications, and provide code examples to illustrate key concepts.':
        "Recursion trips up a lot of people the first time they see it: a function calling itself to solve a smaller version of the same problem. Once it clicks, it's hard to unsee. This article covers how recursion actually works, where it's useful, and where an iterative solution is just the better call, with code examples in Python and C++.",
    },
  },

  // ---- Post 8: pilas-y-colas (intro + conclusion) ------------------------
  8: {
    es: {
      ' en Python, fundamentales para la organización y manejo eficiente de la información. A través de este artículo, exploraremos sus conceptos, características y las implementaciones prácticas en el lenguaje de programación.':
        ' en Python. Casi cualquier algoritmo que uses termina apoyándose en una de las dos, así que vale la pena entender bien cómo funcionan y cuándo elegir una sobre la otra.',
      'Entender los principios LIFO y FIFO que rigen estas estructuras nos permitirá aprovechar su funcionalidad en diversos contextos, optimizando así el rendimiento de nuestras aplicaciones. Profundicemos en su relevancia en el desarrollo de software.':
        'Todo se reduce a dos principios simples, LIFO y FIFO, pero de ahí sale la lógica detrás de undo/redo, colas de impresión, backtracking y hasta cómo Python maneja las llamadas a funciones.',
      'El uso de pilas y colas como estructuras de datos es fundamental en la programación moderna. Brindan soluciones efectivas y organizadas para distintos problemas, desde la evaluación de expresiones hasta la gestión de procesos complejos. Estas estructuras no solo optimizan el rendimiento del código, sino que también aumentan la legibilidad y mantenibilidad del mismo, aspectos cruciales en entornos de desarrollo colaborativo. La inclusión de pilas y colas como parte integral de algoritmos y sistemas permite a los programadores abordar una variedad de problemas con mayor eficacia y claridad. Utilizar correctamente estas estructuras de datos puede marcar la diferencia en el rendimiento y éxito de un proyecto de software.':
        'Pilas y colas parecen básicas, y lo son, pero ahí está su valor. Entre evaluar expresiones, manejar backtracking o simplemente organizar una cola de impresión, elegir la estructura correcta desde el principio te ahorra reescribir lógica más adelante. Vale la pena tenerlas bien internalizadas, así sea que trabajes en Python, C++ o cualquier otro lenguaje.',
    },
    en: {
      'In programming and computer science, understanding data structures is fundamental. Two of the most commonly used linear data structures are ':
        'Stacks and Queues look almost too simple to matter, until you realize how much of what you build depends on one of the two. This article covers how each works, LIFO versus FIFO, where they show up in real code, and how to implement both in Python. ',
      '. Despite their apparent simplicity, they serve as foundational building blocks not only for algorithms but also for complex data manipulations. This article aims to provide an in-depth look at these structures, their properties, differences, applications, and implementations.':
        '.',
    },
  },

  // ---- Post 9: technical-seo-guide (intro) -------------------------------
  9: {
    es: {
      ' El SEO técnico es esencial para garantizar que un sitio web sea accesible y comprensible para los motores de búsqueda. Optimizar la arquitectura, la velocidad y la seguridad del sitio contribuye a mejorar la posición en los resultados de búsqueda. En este artículo, se abordarán diversos aspectos del SEO técnico. Se explorarán principios básicos, optimización de estructura y contenido, así como estrategias para evaluar el rendimiento técnico del sitio web.':
        ' El SEO técnico es la parte de mi trabajo que más disfruto: hacer que un sitio sea rápido, seguro y fácil de rastrear para Google, sin tocar una sola palabra del contenido. En esta guía reviso arquitectura, velocidad, seguridad y cómo medir si todo eso realmente está funcionando.',
    },
    en: {},
  },
}

// Merge the recovery-pass dictionary on top of the original hand-authored
// one. No key collisions expected (EXTRA_REWRITES keys are leaves the
// original dict never successfully matched), but a later spread wins if any
// do collide, since the recovery pass was authored against the true live
// leaf boundaries.
for (const [idStr, dict] of Object.entries(EXTRA_REWRITES)) {
  const id = Number(idStr)
  const existing = REWRITES[id] ?? { es: {}, en: {} }
  REWRITES[id] = {
    es: { ...existing.es, ...dict.es },
    en: { ...existing.en, ...dict.en },
  }
}

// ---------------------------------------------------------------------------
// Tree walker
// ---------------------------------------------------------------------------

function rewriteNode(node: LexicalNode, parentType: string | null, dict: Record<string, string>): LexicalNode {
  if (node === null || node === undefined) return node
  if (node.type === 'block' || node.type === 'table') return node

  if (node.type === 'text' && typeof node.text === 'string') {
    if (parentType === 'link') return node
    const isCode = typeof node.format === 'number' && (node.format & 16) === 16
    if (isCode) return node
    if (parentType !== 'heading' && parentType !== 'paragraph' && parentType !== 'listitem') return node

    const original = node.text
    const authored = dict[original]
    const newText = authored !== undefined ? authored : mechanicalFix(original)
    if (newText === original) return node
    return { ...node, text: newText }
  }

  if (Array.isArray(node.children)) {
    return { ...node, children: node.children.map((child) => rewriteNode(child, node.type, dict)) }
  }

  return node
}

// ---------------------------------------------------------------------------
// Self-check helpers (replicated from scripts/verify-locale-parity.ts lines
// 63-81, adapted locally per the plan's <interfaces> instruction — not
// imported across files)
// ---------------------------------------------------------------------------

function extractText(value: unknown): string {
  if (value === null || value === undefined) return ''
  if (typeof value === 'string') return value
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  if (Array.isArray(value)) return value.map(extractText).join('')
  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>
    let out = ''
    if (typeof obj.text === 'string') out += obj.text
    if (Array.isArray(obj.children)) out += extractText(obj.children)
    if (!('text' in obj) && !('children' in obj)) {
      out += Object.values(obj).map(extractText).join('')
    }
    return out
  }
  return ''
}

// Plan's literal self-check marker list, plus every voceo form this batch's
// mechanical fixer knows about (VOCEO_PAIRS' "from" side, lowercased +
// deduped) — a superset, so the self-check actually verifies the fixer did
// its job instead of only checking the plan's example list.
const VOCEO_MARKERS = Array.from(
  new Set([
    'vos',
    'tenés',
    'podés',
    'querés',
    'sabés',
    'usás',
    'necesitás',
    'trabajás',
    'sospechás',
    'preferís',
    'mirá',
    ...VOCEO_PAIRS.map(([from]) => from.toLowerCase()),
  ]),
)

function findVoceoMarkers(text: string): string[] {
  const found: string[] = []
  for (const marker of VOCEO_MARKERS) {
    const re = new RegExp(`(?<![${WORD_CHAR_CLASS}])${escapeRegExp(marker)}(?![${WORD_CHAR_CLASS}])`, 'i')
    if (re.test(text)) found.push(marker)
  }
  return found
}

function countEmDash(text: string): number {
  return (text.match(/—/g) || []).length
}

// AI-cliché markers (added in the recovery pass — the plan's original
// self-check only covered voceo + em dash; a live spot-check on post id=9
// found "es esencial para garantizar" surviving the first run, so the
// self-check now also gates on these). Checked case-insensitively against
// both locales' extracted text.
const CLICHE_MARKERS = [
  'es esencial', 'es fundamental', 'cabe destacar', 'crucial', 'leverage', 'seamless', 'robust',
  'es importante mencionar', 'es importante destacar', 'no cabe duda', 'sin duda alguna',
]

function findClicheMarkers(text: string): string[] {
  const found: string[] = []
  const lower = text.toLowerCase()
  for (const marker of CLICHE_MARKERS) {
    if (lower.includes(marker.toLowerCase())) found.push(marker)
  }
  return found
}

// Collects every `block`/`table` node (stringified, not descended into) in
// document order, for pre/post byte-identity comparison.
function collectProtectedNodes(node: unknown, out: string[] = []): string[] {
  if (node === null || node === undefined) return out
  if (Array.isArray(node)) {
    for (const item of node) collectProtectedNodes(item, out)
    return out
  }
  if (typeof node === 'object') {
    const obj = node as LexicalNode
    if (obj.type === 'block' || obj.type === 'table') {
      out.push(JSON.stringify(obj))
      return out
    }
    if (Array.isArray(obj.children)) collectProtectedNodes(obj.children, out)
  }
  return out
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Deviation (discovered while writing this batch, NOT auto-fixed — flagged
// instead, see 31-02-SUMMARY.md "Deviations"): post id=9 (technical-seo-guide)
// has NO English translation in production at all — `title.en` is absent
// (only `{ es: "..." }`) and `content.en` is `undefined` (not an empty
// richText doc, genuinely unset). This is a pre-existing i18n gap, not
// something this plan's scope covers: the plan rewrites the VOICE of
// existing prose in both locales, it does not author a brand-new ~1,500-word
// English translation of a technical guide (a much larger deliverable than a
// voice-calibration pass, and Rule 4 territory — an editorial/architectural
// decision, not a bug fix). Skipped for `en`; `es` was rewritten normally.
const KNOWN_MISSING_LOCALE_CONTENT: Partial<Record<number, ('es' | 'en')[]>> = {
  9: ['en'],
}

type Progress = Record<string, 'done'>

function loadProgress(): Progress {
  if (fs.existsSync(PROGRESS_PATH)) {
    return JSON.parse(fs.readFileSync(PROGRESS_PATH, 'utf8')) as Progress
  }
  return {}
}

function saveProgress(progress: Progress) {
  fs.mkdirSync(path.dirname(PROGRESS_PATH), { recursive: true })
  fs.writeFileSync(PROGRESS_PATH, JSON.stringify(progress, null, 2))
}

async function main() {
  const payload = await getPayload({ config })
  const progress = loadProgress()

  // Confirm each id exists live before processing anything.
  for (const id of IDS) {
    const doc = await payload.findByID({ collection: 'posts', id, depth: 0 }).catch(() => null)
    if (!doc) {
      console.error(`FATAL: posts id=${id} does not exist live. Aborting without processing any id.`)
      process.exit(1)
    }
  }

  let allOk = true

  for (const id of IDS) {
    if (progress[String(id)] === 'done') {
      console.log(`id=${id}: already done, skipping.`)
      continue
    }

    console.log(`id=${id}: processing...`)
    const before = await payload.findByID({ collection: 'posts', id, locale: 'all', depth: 0 })
    // NOTE: Payload's richText field value shape is always `{ root: LexicalNode }`,
    // even for a single locale — `content.es`/`content.en` are each `{ root }`
    // wrappers, NOT the root node itself. Every tree walk below operates on
    // `.root`, and every write re-wraps as `{ root: <rewritten> }`.
    const beforeContent = (before as unknown as { content: { es: { root: LexicalNode }; en: { root: LexicalNode } } })
      .content

    const dict = REWRITES[id] ?? { es: {}, en: {} }
    const missingLocales = new Set(KNOWN_MISSING_LOCALE_CONTENT[id] ?? [])
    const protectedBefore = {
      es: collectProtectedNodes(beforeContent.es?.root),
      en: collectProtectedNodes(beforeContent.en?.root),
    }

    for (const locale of ['es', 'en'] as const) {
      const originalRoot = beforeContent[locale]?.root
      if (!originalRoot || missingLocales.has(locale)) {
        console.log(`id=${id}: locale=${locale} has no existing content live — skipping (see KNOWN_MISSING_LOCALE_CONTENT).`)
        continue
      }
      const rewrittenRoot = rewriteNode(originalRoot, null, dict[locale])
      await payload.update({
        collection: 'posts',
        id,
        locale,
        data: { content: { root: rewrittenRoot } as unknown as Record<string, unknown> },
      })
    }

    // Read back to confirm the write persisted, and run the self-check.
    const after = await payload.findByID({ collection: 'posts', id, locale: 'all', depth: 0 })
    const afterContent = (after as unknown as { content: { es: { root: LexicalNode }; en: { root: LexicalNode } } })
      .content

    let idOk = true
    const issues: string[] = []

    // Protected node byte-identity check (only for locales actually written).
    for (const locale of ['es', 'en'] as const) {
      if (missingLocales.has(locale)) continue
      const protectedAfter = collectProtectedNodes(afterContent[locale]?.root)
      if (JSON.stringify(protectedAfter) !== JSON.stringify(protectedBefore[locale])) {
        idOk = false
        issues.push(`${locale}: block/table nodes changed`)
      }
    }

    // Voceo + em dash check (es only for voceo; both for em dash, per plan).
    const esText = extractText(afterContent.es?.root)
    const enText = missingLocales.has('en') ? '' : extractText(afterContent.en?.root)
    const voceoFound = findVoceoMarkers(esText)
    if (voceoFound.length > 0) {
      idOk = false
      issues.push(`es: voceo markers found: ${voceoFound.join(', ')}`)
    }
    const esDash = countEmDash(esText)
    const enDash = countEmDash(enText)
    if (esDash > 0 || enDash > 0) {
      idOk = false
      issues.push(`em dash found: es=${esDash} en=${enDash}`)
    }
    const esCliches = findClicheMarkers(esText)
    const enCliches = findClicheMarkers(enText)
    if (esCliches.length > 0 || enCliches.length > 0) {
      idOk = false
      issues.push(`AI-cliché markers found: es=${esCliches.join(', ')} en=${enCliches.join(', ')}`)
    }

    if (idOk) {
      progress[String(id)] = 'done'
      saveProgress(progress)
      console.log(`id=${id}: OK, marked done.`)
    } else {
      allOk = false
      console.error(`id=${id}: SELF-CHECK FAILED — ${issues.join(' | ')}`)
    }
  }

  if (!allOk) {
    console.error('One or more posts failed self-check. Re-run after investigating.')
    process.exit(1)
  }

  console.log(`\n${IDS.length}/${IDS.length} posts in this batch confirmed done.`)
  process.exit(0)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
