/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    authors: Author;
    categories: Category;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    clientes: Cliente;
    'speaking-events': SpeakingEvent;
    websites: Website;
    redirects: Redirect;
    search: Search;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clientes: ClientesSelect<false> | ClientesSelect<true>;
    'speaking-events': SpeakingEventsSelect<false> | SpeakingEventsSelect<true>;
    websites: WebsitesSelect<false> | WebsitesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    llms: Llm;
    header: Header;
    footer: Footer;
    'featured-content': FeaturedContent;
  };
  globalsSelect: {
    llms: LlmsSelect<false> | LlmsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'featured-content': FeaturedContentSelect<false> | FeaturedContentSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content: {
    layout: (
      | HeroBlock
      | ContentBlock
      | ArchiveBlock
      | CallToActionBlock
      | FAQBlock
      | MediaBlock
      | TestimonialsCarouselBlock
      | ContactFormBlock
      | CodeBlockProps
      | RelatedPostsBlockType
      | TableOfContentsBlockType
      | ResultsSectionBlock
      | SectionBlock
      | FeaturedPostsBlock
      | FeaturedCaseStudiesBlock
      | FeaturedWebsitesBlock
      | ClientLogosBlock
      | AboutSectionBlock
      | ServicesShowcaseBlock
      | ServiceScopeCardBlock
      | RelatedCaseStudyBlockBlock
      | LocalProofSectionBlock
      | CodeFixesBlock
      | AuditOfferBlock
    )[];
  };
  slug?: string | null;
  /**
   * Editorial reference only — the primary keyword this page/profile is written toward. Does not affect SEO meta tags or trigger any external API call.
   */
  targetKeyword?: {
    en?: string | null;
    es?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant: 'home' | 'listing' | 'post-header' | 'case-study-header' | 'local-landing';
  title?: string | null;
  subtitle?: string | null;
  media?: (number | null) | Media;
  /**
   * Optional CTA buttons rendered below the hero copy.
   */
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional breadcrumb trail, only rendered on the Listing variant.
   */
  breadcrumbs?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Nombre de la ciudad mostrado en el badge (ej: "Madrid"). Solo variante Local Landing.
   */
  cityName?: string | null;
  /**
   * Texto del stat inline junto al check-icon (ej: "+40 proyectos entregados"). Solo variante Local Landing.
   */
  inlineStat?: string | null;
  /**
   * Lado donde se posiciona el anillo decorativo. Solo variante Local Landing.
   */
  ringSide?: ('left' | 'right') | null;
  /**
   * Opacidad del anillo decorativo (0 a 1). Solo variante Local Landing.
   */
  ringOpacity?: number | null;
  /**
   * Espeja el anillo decorativo horizontalmente. Solo variante Local Landing.
   */
  ringFlipX?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroImage?: (number | null) | Media;
  author: number | Author;
  categories?: (number | Category)[] | null;
  publishedAt?: string | null;
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  jobTitle?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  /**
   * E-E-A-T credentials, e.g. "10+ años en SEO técnico", "Google Analytics Certification"
   */
  credentials?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Temas de especialización técnica, renderizados como tags en el author page
   */
  expertise?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        degree: string;
        institution: string;
        logo?: (number | null) | Media;
        startDate?: string | null;
        endDate?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  experience?:
    | {
        company: string;
        role: string;
        startDate?: string | null;
        endDate?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  yearsExperience?: number | null;
  socialLinks?:
    | {
        platform: 'linkedin' | 'github' | 'x' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  /**
   * Editorial reference only — the primary keyword this page/profile is written toward. Does not affect SEO meta tags or trigger any external API call.
   */
  targetKeyword?: {
    en?: string | null;
    es?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  description?: string | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  relationTo: 'posts' | 'case-studies' | 'websites';
  mode?: ('latest' | 'manual') | null;
  limit?: number | null;
  selectedDocs?:
    | (
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'case-studies';
            value: number | CaseStudy;
          }
        | {
            relationTo: 'websites';
            value: number | Website;
          }
      )[]
    | null;
  /**
   * Show category filter tabs above the grid (posts only).
   */
  enableCategoryFilter?: boolean | null;
  /**
   * Shown when a category filter (or manual selection) yields 0 results.
   */
  emptyStateHeading?: string | null;
  emptyStateBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archiveBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  heroMetric?: string | null;
  heroSubtitle?: string | null;
  client?: (number | null) | Cliente;
  sector?: string | null;
  period?: string | null;
  services?:
    | {
        service: string;
        id?: string | null;
      }[]
    | null;
  kpis?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  clientContext?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challenge?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  solution?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Testimonio embebido entre "La solución" y "Resultados"
   */
  testimonialSection?: TestimonialSectionBlock[] | null;
  results?: {
    periodBefore?: string | null;
    periodAfter?: string | null;
    metrics?:
      | {
          label: string;
          before: string;
          after: string;
          id?: string | null;
        }[]
      | null;
  };
  conclusion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  author?: (number | null) | Author;
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes".
 */
export interface Cliente {
  id: number;
  name: string;
  logo: number | Media;
  websiteUrl?: string | null;
  /**
   * Tipo de trabajo hecho para este cliente. Agrupa el muro de logos en la portada.
   */
  workType?: ('seo' | 'desarrollo' | 'optimizacion') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialSectionBlock".
 */
export interface TestimonialSectionBlock {
  quote: string;
  authorName: string;
  authorRole: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "websites".
 */
export interface Website {
  id: number;
  title: string;
  role?: string | null;
  industry?: string | null;
  year?: number | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stack?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  challenges?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  screenshots?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  lighthouse?: {
    performance?: number | null;
    accessibility?: number | null;
    bestPractices?: number | null;
    seo?: number | null;
  };
  lighthouseCapturedAt: string;
  client?: (number | null) | Cliente;
  relatedCaseStudy?: (number | null) | CaseStudy;
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  title?: string | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsCarouselBlock".
 */
export interface TestimonialsCarouselBlock {
  title?: string | null;
  showRating?: boolean | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  /**
   * Texto pequeño sobre el título
   */
  eyebrow?: string | null;
  /**
   * Título del formulario
   */
  title: string;
  /**
   * Descripción del formulario
   */
  description?: string | null;
  /**
   * Texto del botón de enviar
   */
  submitLabel?: string | null;
  /**
   * Título del panel lateral derecho (ej: "Charlemos sobre tu próximo proyecto")
   */
  sidebarTitle?: string | null;
  /**
   * Descripción del panel lateral (ej: disponibilidad, tipo de proyectos)
   */
  sidebarDescription?: string | null;
  /**
   * Texto de prueba social en la parte inferior del panel (ej: "Más de 50 proyectos completados")
   */
  socialProofText?: string | null;
  /**
   * Información de contacto mostrada al lado del formulario
   */
  contactInfo?:
    | {
        icon: 'mail' | 'phone' | 'map-pin' | 'linkedin' | 'github';
        title: string;
        value: string;
        /**
         * URL o enlace (ej: mailto:, tel:, https://)
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactFormBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlockProps".
 */
export interface CodeBlockProps {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedPostsBlockType".
 */
export interface RelatedPostsBlockType {
  /**
   * Título de la sección (ej: "Artículos relacionados")
   */
  title?: string | null;
  /**
   * Posts relacionados específicos (opcional)
   */
  posts?: (number | Post)[] | null;
  /**
   * Auto-seleccionar posts por categoría si no hay posts manuales
   */
  autoSelect?: boolean | null;
  /**
   * Número máximo de posts relacionados
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedPosts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableOfContentsBlockType".
 */
export interface TableOfContentsBlockType {
  /**
   * Título de la tabla de contenidos
   */
  title?: string | null;
  /**
   * Posición del TOC en desktop
   */
  position?: ('left' | 'right' | 'top') | null;
  /**
   * Hacer el TOC sticky (pegado al scroll)
   */
  sticky?: boolean | null;
  /**
   * Nivel mínimo de encabezado a incluir
   */
  minHeadingLevel?: ('2' | '3') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tableOfContentsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsSectionBlock".
 */
export interface ResultsSectionBlock {
  /**
   * Título de la sección (ej: "Resultados Cuantificables")
   */
  title: string;
  /**
   * Descripción opcional debajo del título
   */
  description?: string | null;
  stats: {
    /**
     * Valor de la estadística (ej: "40%", "3x", "+50K")
     */
    value: string;
    /**
     * Descripción de la estadística
     */
    label: string;
    id?: string | null;
  }[];
  /**
   * Color de fondo de la sección
   */
  backgroundColor?: ('gray' | 'white' | 'primary') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'resultsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlock".
 */
export interface SectionBlock {
  container?: ('container' | 'full') | null;
  paddingY?: ('none' | 'sm' | 'md' | 'lg') | null;
  backgroundStyle?: ('none' | 'color' | 'image') | null;
  backgroundColor?: ('bg-transparent' | 'bg-gray-50 dark:bg-card-dark' | 'bg-blue-50' | 'bg-card') | null;
  backgroundMedia?: (number | null) | Media;
  /**
   * ID de ancla para navegación (#mi-seccion)
   */
  anchorId?: string | null;
  /**
   * Clases CSS adicionales (Tailwind)
   */
  className?: string | null;
  blocks?: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPostsBlock".
 */
export interface FeaturedPostsBlock {
  /**
   * Section heading — editable per page instance.
   */
  title?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredPostsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCaseStudiesBlock".
 */
export interface FeaturedCaseStudiesBlock {
  /**
   * Section heading — editable per page instance.
   */
  title?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredCaseStudiesBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedWebsitesBlock".
 */
export interface FeaturedWebsitesBlock {
  /**
   * Section heading — editable per page instance.
   */
  title?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredWebsitesBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientLogosBlock".
 */
export interface ClientLogosBlock {
  title?: string | null;
  /**
   * Leave empty to show all clients.
   */
  clients?: (number | Cliente)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'clientLogosBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSectionBlock".
 */
export interface AboutSectionBlock {
  /**
   * Texto corto sobre el título (ej: "Sobre mí")
   */
  eyebrow?: string | null;
  title: string;
  paragraphs: {
    text: string;
    id?: string | null;
  }[];
  photo?: (number | null) | Media;
  /**
   * Exactamente 4 items: icono + título + descripción (grid "Mi enfoque en Consultoría Técnica")
   */
  features?:
    | {
        icon:
          | 'zap'
          | 'monitor'
          | 'code'
          | 'trendingUp'
          | 'shield'
          | 'rocket'
          | 'palette'
          | 'lightbulb'
          | 'target'
          | 'layers'
          | 'cpu'
          | 'database'
          | 'globe'
          | 'search'
          | 'settings'
          | 'smartphone'
          | 'server'
          | 'lock'
          | 'gauge'
          | 'sparkles'
          | 'wrench'
          | 'lineChart'
          | 'checkCircle'
          | 'barChart';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Texto del botón CTA (opcional)
   */
  ctaText?: string | null;
  /**
   * URL o ancla del CTA, ej: #contact (opcional)
   */
  ctaLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesShowcaseBlock".
 */
export interface ServicesShowcaseBlock {
  /**
   * Section heading — editable per page instance.
   */
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceScopeCardBlock".
 */
export interface ServiceScopeCardBlock {
  /**
   * Optional card heading — defaults to "Alcance de este servicio"/"Service scope" in the component if empty.
   */
  title?: string | null;
  /**
   * "Qué incluye" / "What's included"
   */
  scope: string;
  /**
   * "Qué vas a lograr" / "What you'll get"
   */
  outcome: string;
  /**
   * Short freeform phrase (e.g. "2-3 semanas") — NOT a number field, timelines vary in phrasing per service.
   */
  timeline: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'serviceScopeCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedCaseStudyBlockBlock".
 */
export interface RelatedCaseStudyBlockBlock {
  /**
   * Optional heading — defaults to "Un caso real de cómo trabajo"/"A real example of how I work" in the component if empty.
   */
  title?: string | null;
  /**
   * Honest-framing sentence written per landing (not a single hardcoded string) — must not imply the case study is specific to this exact service.
   */
  framingText?: string | null;
  /**
   * If empty, the component falls back to the most recently created case study.
   */
  caseStudy?: (number | null) | CaseStudy;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedCaseStudyBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocalProofSectionBlock".
 */
export interface LocalProofSectionBlock {
  /**
   * Exactamente 3 estadisticas numericas locales.
   */
  stats: {
    /**
     * Valor de la estadistica (ej: "+40", "98%", "5 anos")
     */
    value: string;
    /**
     * Descripcion de la estadistica
     */
    label: string;
    id?: string | null;
  }[];
  /**
   * Testimonio local con nombre y negocio.
   */
  testimonial: {
    quote: string;
    authorName: string;
    authorBusiness: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'localProofSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeFixesBlock".
 */
export interface CodeFixesBlock {
  /**
   * Ej: "Este sitio es el caso de estudio".
   */
  title: string;
  /**
   * Una o dos frases. Por qué se muestran los fixes de este repo y no los de un cliente.
   */
  intro?: string | null;
  /**
   * URL del repositorio público. Es lo que vuelve verificable todo el bloque: sin esto, el código es una captura que hay que creer.
   */
  repoUrl?: string | null;
  /**
   * Texto del enlace al repo. Ej: "Ver el repositorio".
   */
  repoLabel?: string | null;
  /**
   * Dos o tres. Cada uno tiene que ser un commit real de este repo — el código pegado acá debe ser el que está en ese commit.
   */
  fixes?:
    | {
        /**
         * Qué estaba roto, en lenguaje de síntoma, no de solución. Ej: "Google recibía dos hreflang que se contradecían".
         */
        symptom: string;
        /**
         * La causa técnica real, en una o dos frases. Es la parte que ningún competidor cuenta y la razón de ser del bloque.
         */
        cause?: string | null;
        /**
         * Ruta del archivo, tal cual está en el repo.
         */
        filePath: string;
        language?: ('ts' | 'tsx' | 'js' | 'json' | 'sql' | 'html' | 'bash') | null;
        /**
         * El fragmento del cambio. Cortá al mínimo legible: entre 5 y 25 líneas. Nadie lee un diff de 200 en una portada.
         */
        code: string;
        /**
         * URL del commit en GitHub.
         */
        commitUrl?: string | null;
        /**
         * SHA corto, 7 caracteres.
         */
        commitSha?: string | null;
        /**
         * Qué cambió después, si es medible. Dejalo vacío antes que estimar: un dato que falta se queda faltando.
         */
        outcome?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'codeFixesBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AuditOfferBlock".
 */
export interface AuditOfferBlock {
  title: string;
  description?: string | null;
  /**
   * El precio, tal cual se muestra. Ej: "600 USD". Editable desde acá justamente para poder subirlo sin tocar código.
   */
  price?: string | null;
  /**
   * Qué es ese precio. Ej: "Auditoría SEO técnica completa".
   */
  priceCaption?: string | null;
  /**
   * La mecánica del crédito: el importe se descuenta al contratar la implementación. Es lo que saca el riesgo de la decisión, así que va visible, no en letra chica.
   */
  creditNote?: string | null;
  /**
   * Qué incluye la auditoría. Concreto y verificable: el visitante está por pagar, y lo vago es lo que hace dudar.
   */
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Plazo de entrega. Ej: "Entrega en 10 días hábiles".
   */
  deliveryNote?: string | null;
  /**
   * El CTA. Uno solo en primario: la portada pide una única acción.
   */
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'auditOfferBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role: string;
  company: string;
  testimonial: string;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speaking-events".
 */
export interface SpeakingEvent {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Qué hizo Juan en el evento, p.ej. "Ponente", "Co-instructor"
   */
  role?: string | null;
  coSpeakers?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional — dejar vacío si no hay fecha exacta confirmada, no inventar
   */
  date?: string | null;
  location?: string | null;
  attendeeCount?: number | null;
  link?: string | null;
  flyer?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'categories';
          value: number | Category;
        } | null)
      | ({
          relationTo: 'authors';
          value: number | Author;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'case-studies';
        value: number | CaseStudy;
      }
    | {
        relationTo: 'authors';
        value: number | Author;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
  };
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
  };
  caseStudies?: {
    /**
     * Allow clients to find case-studies.
     */
    find?: boolean | null;
    /**
     * Allow clients to create case-studies.
     */
    create?: boolean | null;
    /**
     * Allow clients to update case-studies.
     */
    update?: boolean | null;
  };
  authors?: {
    /**
     * Allow clients to find authors.
     */
    find?: boolean | null;
    /**
     * Allow clients to create authors.
     */
    create?: boolean | null;
    /**
     * Allow clients to update authors.
     */
    update?: boolean | null;
  };
  testimonials?: {
    /**
     * Allow clients to find testimonials.
     */
    find?: boolean | null;
    /**
     * Allow clients to create testimonials.
     */
    create?: boolean | null;
    /**
     * Allow clients to update testimonials.
     */
    update?: boolean | null;
  };
  clientes?: {
    /**
     * Allow clients to find clientes.
     */
    find?: boolean | null;
    /**
     * Allow clients to create clientes.
     */
    create?: boolean | null;
    /**
     * Allow clients to update clientes.
     */
    update?: boolean | null;
  };
  speakingEvents?: {
    /**
     * Allow clients to find speaking-events.
     */
    find?: boolean | null;
    /**
     * Allow clients to create speaking-events.
     */
    create?: boolean | null;
    /**
     * Allow clients to update speaking-events.
     */
    update?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
  };
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  llms?: {
    /**
     * Allow clients to find llms global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update llms global.
     */
    update?: boolean | null;
  };
  header?: {
    /**
     * Allow clients to find header global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update header global.
     */
    update?: boolean | null;
  };
  footer?: {
    /**
     * Allow clients to find footer global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update footer global.
     */
    update?: boolean | null;
  };
  featuredContent?: {
    /**
     * Allow clients to find featured-content global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update featured-content global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clientes';
        value: number | Cliente;
      } | null)
    | ({
        relationTo: 'speaking-events';
        value: number | SpeakingEvent;
      } | null)
    | ({
        relationTo: 'websites';
        value: number | Website;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?:
    | T
    | {
        layout?:
          | T
          | {
              hero?: T | HeroBlockSelect<T>;
              content?: T | ContentBlockSelect<T>;
              archiveBlock?: T | ArchiveBlockSelect<T>;
              callToAction?: T | CallToActionBlockSelect<T>;
              faq?: T | FAQBlockSelect<T>;
              mediaBlock?: T | MediaBlockSelect<T>;
              testimonialsCarousel?: T | TestimonialsCarouselBlockSelect<T>;
              contactFormBlock?: T | ContactFormBlockSelect<T>;
              code?: T | CodeBlockPropsSelect<T>;
              relatedPosts?: T | RelatedPostsBlockTypeSelect<T>;
              tableOfContentsBlock?: T | TableOfContentsBlockTypeSelect<T>;
              resultsSection?: T | ResultsSectionBlockSelect<T>;
              section?: T | SectionBlockSelect<T>;
              featuredPostsBlock?: T | FeaturedPostsBlockSelect<T>;
              featuredCaseStudiesBlock?: T | FeaturedCaseStudiesBlockSelect<T>;
              featuredWebsitesBlock?: T | FeaturedWebsitesBlockSelect<T>;
              clientLogosBlock?: T | ClientLogosBlockSelect<T>;
              aboutSection?: T | AboutSectionBlockSelect<T>;
              servicesShowcase?: T | ServicesShowcaseBlockSelect<T>;
              serviceScopeCard?: T | ServiceScopeCardBlockSelect<T>;
              relatedCaseStudyBlock?: T | RelatedCaseStudyBlockBlockSelect<T>;
              localProofSection?: T | LocalProofSectionBlockSelect<T>;
              codeFixesBlock?: T | CodeFixesBlockSelect<T>;
              auditOfferBlock?: T | AuditOfferBlockSelect<T>;
            };
      };
  slug?: T;
  targetKeyword?:
    | T
    | {
        en?: T;
        es?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  title?: T;
  subtitle?: T;
  media?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  breadcrumbs?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  cityName?: T;
  inlineStat?: T;
  ringSide?: T;
  ringOpacity?: T;
  ringFlipX?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  relationTo?: T;
  mode?: T;
  limit?: T;
  selectedDocs?: T;
  enableCategoryFilter?: T;
  emptyStateHeading?: T;
  emptyStateBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  title?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsCarouselBlock_select".
 */
export interface TestimonialsCarouselBlockSelect<T extends boolean = true> {
  title?: T;
  showRating?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  submitLabel?: T;
  sidebarTitle?: T;
  sidebarDescription?: T;
  socialProofText?: T;
  contactInfo?:
    | T
    | {
        icon?: T;
        title?: T;
        value?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlockProps_select".
 */
export interface CodeBlockPropsSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedPostsBlockType_select".
 */
export interface RelatedPostsBlockTypeSelect<T extends boolean = true> {
  title?: T;
  posts?: T;
  autoSelect?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableOfContentsBlockType_select".
 */
export interface TableOfContentsBlockTypeSelect<T extends boolean = true> {
  title?: T;
  position?: T;
  sticky?: T;
  minHeadingLevel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsSectionBlock_select".
 */
export interface ResultsSectionBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlock_select".
 */
export interface SectionBlockSelect<T extends boolean = true> {
  container?: T;
  paddingY?: T;
  backgroundStyle?: T;
  backgroundColor?: T;
  backgroundMedia?: T;
  anchorId?: T;
  className?: T;
  blocks?:
    | T
    | {
        callToAction?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archiveBlock?: T | ArchiveBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPostsBlock_select".
 */
export interface FeaturedPostsBlockSelect<T extends boolean = true> {
  title?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCaseStudiesBlock_select".
 */
export interface FeaturedCaseStudiesBlockSelect<T extends boolean = true> {
  title?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedWebsitesBlock_select".
 */
export interface FeaturedWebsitesBlockSelect<T extends boolean = true> {
  title?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientLogosBlock_select".
 */
export interface ClientLogosBlockSelect<T extends boolean = true> {
  title?: T;
  clients?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSectionBlock_select".
 */
export interface AboutSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  photo?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  ctaText?: T;
  ctaLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesShowcaseBlock_select".
 */
export interface ServicesShowcaseBlockSelect<T extends boolean = true> {
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceScopeCardBlock_select".
 */
export interface ServiceScopeCardBlockSelect<T extends boolean = true> {
  title?: T;
  scope?: T;
  outcome?: T;
  timeline?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedCaseStudyBlockBlock_select".
 */
export interface RelatedCaseStudyBlockBlockSelect<T extends boolean = true> {
  title?: T;
  framingText?: T;
  caseStudy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocalProofSectionBlock_select".
 */
export interface LocalProofSectionBlockSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorBusiness?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeFixesBlock_select".
 */
export interface CodeFixesBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  repoUrl?: T;
  repoLabel?: T;
  fixes?:
    | T
    | {
        symptom?: T;
        cause?: T;
        filePath?: T;
        language?: T;
        code?: T;
        commitUrl?: T;
        commitSha?: T;
        outcome?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AuditOfferBlock_select".
 */
export interface AuditOfferBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  price?: T;
  priceCaption?: T;
  creditNote?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  deliveryNote?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  author?: T;
  categories?: T;
  publishedAt?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  jobTitle?: T;
  bio?: T;
  avatar?: T;
  credentials?:
    | T
    | {
        label?: T;
        id?: T;
      };
  expertise?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  education?:
    | T
    | {
        degree?: T;
        institution?: T;
        logo?: T;
        startDate?: T;
        endDate?: T;
        description?: T;
        id?: T;
      };
  experience?:
    | T
    | {
        company?: T;
        role?: T;
        startDate?: T;
        endDate?: T;
        description?: T;
        id?: T;
      };
  yearsExperience?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  targetKeyword?:
    | T
    | {
        en?: T;
        es?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  heroMetric?: T;
  heroSubtitle?: T;
  client?: T;
  sector?: T;
  period?: T;
  services?:
    | T
    | {
        service?: T;
        id?: T;
      };
  kpis?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  clientContext?: T;
  challenge?:
    | T
    | {
        text?: T;
        id?: T;
      };
  solution?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  testimonialSection?:
    | T
    | {
        testimonialSection?: T | TestimonialSectionBlockSelect<T>;
      };
  results?:
    | T
    | {
        periodBefore?: T;
        periodAfter?: T;
        metrics?:
          | T
          | {
              label?: T;
              before?: T;
              after?: T;
              id?: T;
            };
      };
  conclusion?: T;
  heroImage?: T;
  author?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialSectionBlock_select".
 */
export interface TestimonialSectionBlockSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorRole?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  testimonial?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes_select".
 */
export interface ClientesSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  websiteUrl?: T;
  workType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speaking-events_select".
 */
export interface SpeakingEventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  role?: T;
  coSpeakers?:
    | T
    | {
        name?: T;
        id?: T;
      };
  date?: T;
  location?: T;
  attendeeCount?: T;
  link?: T;
  flyer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "websites_select".
 */
export interface WebsitesSelect<T extends boolean = true> {
  title?: T;
  role?: T;
  industry?: T;
  year?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stack?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  challenges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  screenshots?:
    | T
    | {
        image?: T;
        id?: T;
      };
  lighthouse?:
    | T
    | {
        performance?: T;
        accessibility?: T;
        bestPractices?: T;
        seo?: T;
      };
  lighthouseCapturedAt?: T;
  client?: T;
  relatedCaseStudy?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  posts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  caseStudies?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  authors?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  testimonials?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  clientes?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  speakingEvents?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  users?:
    | T
    | {
        find?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  llms?:
    | T
    | {
        find?: T;
        update?: T;
      };
  header?:
    | T
    | {
        find?: T;
        update?: T;
      };
  footer?:
    | T
    | {
        find?: T;
        update?: T;
      };
  featuredContent?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Files for AI agents (llms.txt standard). Editable here; published at /llms.txt and /llms-full.txt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llms".
 */
export interface Llm {
  id: number;
  llmsTxt: string;
  llmsFull: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide navigation, logo, and CTA button — editable without touching code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer columns, social links, legal links, and copyright text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title?: string | null;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Columnas computadas en render time desde Posts/CaseStudies (ultimos N por fecha), no curadas manualmente.
   */
  dynamicColumns?:
    | {
        title?: string | null;
        source: 'latestPosts' | 'latestCaseStudies';
        limit?: number | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'linkedin' | 'github' | 'x' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manual curation of which posts/case studies appear in "featured" sections site-wide (Home, Blog listing) — not derived from recency alone.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-content".
 */
export interface FeaturedContent {
  id: number;
  /**
   * Drives the Home page and Blog listing "Featured Posts" sections.
   */
  featuredPosts?: (number | Post)[] | null;
  /**
   * Drives the Home page "Featured Case Studies" section.
   */
  featuredCaseStudies?: (number | CaseStudy)[] | null;
  /**
   * Drives the Home page "Featured Websites" section.
   */
  featuredWebsites?: (number | Website)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llms_select".
 */
export interface LlmsSelect<T extends boolean = true> {
  llmsTxt?: T;
  llmsFull?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  dynamicColumns?:
    | T
    | {
        title?: T;
        source?: T;
        limit?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-content_select".
 */
export interface FeaturedContentSelect<T extends boolean = true> {
  featuredPosts?: T;
  featuredCaseStudies?: T;
  featuredWebsites?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'websites';
          value: number | Website;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}